var _1967_76ers = [
  {
    "G": 1,
    "Date": "Sat Oct 15 1966",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 128,
    "Opp": 112,
    "W": 1,
    "L": 0,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 2,
    "Date": "Fri Oct 21 1966",
    "": 0,
    "Opponent": "St. Louis Hawks",
    "Tm": 119,
    "Opp": 110,
    "W": 2,
    "L": 0,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 3,
    "Date": "Sat Oct 22 1966",
    "": 0,
    "Opponent": "Baltimore Bullets",
    "Tm": 141,
    "Opp": 112,
    "W": 3,
    "L": 0,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 4,
    "Date": "Tue Oct 25 1966",
    "": 0,
    "Opponent": "Baltimore Bullets",
    "Tm": 130,
    "Opp": 110,
    "W": 4,
    "L": 0,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 5,
    "Date": "Sat Oct 29 1966",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 138,
    "Opp": 96,
    "W": 5,
    "L": 0,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 6,
    "Date": "Thu Nov 3 1966",
    "": 0,
    "Opponent": "St. Louis Hawks",
    "Tm": 120,
    "Opp": 108,
    "W": 6,
    "L": 0,
    "Streak": "W 6",
    "Notes": "at Pittsburgh PA"
  },
  {
    "G": 7,
    "Date": "Fri Nov 4 1966",
    "": 0,
    "Opponent": "San Francisco Warriors",
    "Tm": 134,
    "Opp": 129,
    "W": 7,
    "L": 0,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 8,
    "Date": "Sat Nov 5 1966",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 87,
    "Opp": 105,
    "W": 7,
    "L": 1,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 9,
    "Date": "Tue Nov 8 1966",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 118,
    "Opp": 100,
    "W": 8,
    "L": 1,
    "Streak": "W 1",
    "Notes": "at New York NY"
  },
  {
    "G": 10,
    "Date": "Fri Nov 11 1966",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 126,
    "Opp": 113,
    "W": 9,
    "L": 1,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 11,
    "Date": "Sat Nov 12 1966",
    "": 0,
    "Opponent": "Cincinnati Royals",
    "Tm": 112,
    "Opp": 98,
    "W": 10,
    "L": 1,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 12,
    "Date": "Sun Nov 13 1966",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 132,
    "Opp": 126,
    "W": 11,
    "L": 1,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 13,
    "Date": "Tue Nov 15 1966",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 113,
    "Opp": 109,
    "W": 12,
    "L": 1,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 14,
    "Date": "Wed Nov 16 1966",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 117,
    "Opp": 108,
    "W": 13,
    "L": 1,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 15,
    "Date": "Fri Nov 18 1966",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 145,
    "Opp": 120,
    "W": 14,
    "L": 1,
    "Streak": "W 7",
    "Notes": "at Boston MA"
  },
  {
    "G": 16,
    "Date": "Sat Nov 19 1966",
    "": 0,
    "Opponent": "Cincinnati Royals",
    "Tm": 134,
    "Opp": 110,
    "W": 15,
    "L": 1,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 17,
    "Date": "Wed Nov 23 1966",
    "": 0,
    "Opponent": "Cincinnati Royals",
    "Tm": 106,
    "Opp": 111,
    "W": 15,
    "L": 2,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 18,
    "Date": "Thu Nov 24 1966",
    "": 0,
    "Opponent": "San Francisco Warriors",
    "Tm": 140,
    "Opp": 123,
    "W": 16,
    "L": 2,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 19,
    "Date": "Fri Nov 25 1966",
    "": 0,
    "Opponent": "Baltimore Bullets",
    "Tm": 129,
    "Opp": 115,
    "W": 17,
    "L": 2,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 20,
    "Date": "Sat Nov 26 1966",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 131,
    "Opp": 123,
    "W": 18,
    "L": 2,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 21,
    "Date": "Tue Nov 29 1966",
    "": 0,
    "Opponent": "St. Louis Hawks",
    "Tm": 137,
    "Opp": 116,
    "W": 19,
    "L": 2,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 22,
    "Date": "Wed Nov 30 1966",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 128,
    "Opp": 119,
    "W": 20,
    "L": 2,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 23,
    "Date": "Fri Dec 2 1966",
    "": 0,
    "Opponent": "Los Angeles Lakers",
    "Tm": 138,
    "Opp": 130,
    "W": 21,
    "L": 2,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 24,
    "Date": "Sat Dec 3 1966",
    "": 0,
    "Opponent": "Baltimore Bullets",
    "Tm": 137,
    "Opp": 120,
    "W": 22,
    "L": 2,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 25,
    "Date": "Tue Dec 6 1966",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 129,
    "Opp": 119,
    "W": 23,
    "L": 2,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 26,
    "Date": "Wed Dec 7 1966",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 117,
    "Opp": 103,
    "W": 24,
    "L": 2,
    "Streak": "W 9",
    "Notes": 0
  },
  {
    "G": 27,
    "Date": "Fri Dec 9 1966",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 112,
    "Opp": 107,
    "W": 25,
    "L": 2,
    "Streak": "W 10",
    "Notes": 0
  },
  {
    "G": 28,
    "Date": "Sat Dec 10 1966",
    "": 0,
    "Opponent": "St. Louis Hawks",
    "Tm": 133,
    "Opp": 123,
    "W": 26,
    "L": 2,
    "Streak": "W 11",
    "Notes": 0
  },
  {
    "G": 29,
    "Date": "Sun Dec 11 1966",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 103,
    "Opp": 117,
    "W": 26,
    "L": 3,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 30,
    "Date": "Tue Dec 13 1966",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 127,
    "Opp": 112,
    "W": 27,
    "L": 3,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 31,
    "Date": "Fri Dec 16 1966",
    "": 0,
    "Opponent": "St. Louis Hawks",
    "Tm": 124,
    "Opp": 113,
    "W": 28,
    "L": 3,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 32,
    "Date": "Sat Dec 17 1966",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 120,
    "Opp": 105,
    "W": 29,
    "L": 3,
    "Streak": "W 3",
    "Notes": "at Syracuse NY"
  },
  {
    "G": 33,
    "Date": "Wed Dec 21 1966",
    "": 0,
    "Opponent": "Los Angeles Lakers",
    "Tm": 129,
    "Opp": 123,
    "W": 30,
    "L": 3,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 34,
    "Date": "Thu Dec 22 1966",
    "": 0,
    "Opponent": "San Francisco Warriors",
    "Tm": 116,
    "Opp": 114,
    "W": 31,
    "L": 3,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 35,
    "Date": "Fri Dec 23 1966",
    "": 0,
    "Opponent": "Los Angeles Lakers",
    "Tm": 118,
    "Opp": 107,
    "W": 32,
    "L": 3,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 36,
    "Date": "Mon Dec 26 1966",
    "": 0,
    "Opponent": "Cincinnati Royals",
    "Tm": 134,
    "Opp": 118,
    "W": 33,
    "L": 3,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 37,
    "Date": "Wed Dec 28 1966",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 113,
    "Opp": 108,
    "W": 34,
    "L": 3,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 38,
    "Date": "Fri Dec 30 1966",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 137,
    "Opp": 113,
    "W": 35,
    "L": 3,
    "Streak": "W 9",
    "Notes": "at Fort Wayne IN"
  },
  {
    "G": 39,
    "Date": "Tue Jan 3 1967",
    "": "OT",
    "Opponent": "New York Knicks",
    "Tm": 148,
    "Opp": 142,
    "W": 36,
    "L": 3,
    "Streak": "W 10",
    "Notes": 0
  },
  {
    "G": 40,
    "Date": "Wed Jan 4 1967",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 136,
    "Opp": 115,
    "W": 37,
    "L": 3,
    "Streak": "W 11",
    "Notes": 0
  },
  {
    "G": 41,
    "Date": "Thu Jan 5 1967",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 104,
    "Opp": 112,
    "W": 37,
    "L": 4,
    "Streak": "L 1",
    "Notes": "at Pittsburgh PA"
  },
  {
    "G": 42,
    "Date": "Fri Jan 6 1967",
    "": "OT",
    "Opponent": "Baltimore Bullets",
    "Tm": 121,
    "Opp": 115,
    "W": 38,
    "L": 4,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 43,
    "Date": "Sun Jan 8 1967",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 117,
    "Opp": 108,
    "W": 39,
    "L": 4,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 44,
    "Date": "Fri Jan 13 1967",
    "": 0,
    "Opponent": "St. Louis Hawks",
    "Tm": 125,
    "Opp": 107,
    "W": 40,
    "L": 4,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 45,
    "Date": "Sun Jan 15 1967",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 110,
    "Opp": 95,
    "W": 41,
    "L": 4,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 46,
    "Date": "Tue Jan 17 1967",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 119,
    "Opp": 111,
    "W": 42,
    "L": 4,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 47,
    "Date": "Wed Jan 18 1967",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 113,
    "Opp": 105,
    "W": 43,
    "L": 4,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 48,
    "Date": "Thu Jan 19 1967",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 127,
    "Opp": 102,
    "W": 44,
    "L": 4,
    "Streak": "W 7",
    "Notes": "at Pittsburgh PA"
  },
  {
    "G": 49,
    "Date": "Fri Jan 20 1967",
    "": 0,
    "Opponent": "Los Angeles Lakers",
    "Tm": 119,
    "Opp": 108,
    "W": 45,
    "L": 4,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 50,
    "Date": "Mon Jan 23 1967",
    "": 0,
    "Opponent": "St. Louis Hawks",
    "Tm": 112,
    "Opp": 105,
    "W": 46,
    "L": 4,
    "Streak": "W 9",
    "Notes": "at Memphis TN"
  },
  {
    "G": 51,
    "Date": "Tue Jan 24 1967",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 106,
    "Opp": 118,
    "W": 46,
    "L": 5,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 52,
    "Date": "Fri Jan 27 1967",
    "": 0,
    "Opponent": "Cincinnati Royals",
    "Tm": 110,
    "Opp": 107,
    "W": 47,
    "L": 5,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 53,
    "Date": "Sun Jan 29 1967",
    "": 0,
    "Opponent": "St. Louis Hawks",
    "Tm": 108,
    "Opp": 114,
    "W": 47,
    "L": 6,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 54,
    "Date": "Wed Feb 1 1967",
    "": 0,
    "Opponent": "Los Angeles Lakers",
    "Tm": 133,
    "Opp": 143,
    "W": 47,
    "L": 7,
    "Streak": "L 2",
    "Notes": 0
  },
  {
    "G": 55,
    "Date": "Thu Feb 2 1967",
    "": 0,
    "Opponent": "San Francisco Warriors",
    "Tm": 120,
    "Opp": 137,
    "W": 47,
    "L": 8,
    "Streak": "L 3",
    "Notes": "at Oakland CA"
  },
  {
    "G": 56,
    "Date": "Sat Feb 4 1967",
    "": 0,
    "Opponent": "San Francisco Warriors",
    "Tm": 140,
    "Opp": 127,
    "W": 48,
    "L": 8,
    "Streak": "W 1",
    "Notes": "at Oakland CA"
  },
  {
    "G": 57,
    "Date": "Sun Feb 5 1967",
    "": 0,
    "Opponent": "Los Angeles Lakers",
    "Tm": 130,
    "Opp": 123,
    "W": 49,
    "L": 8,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 58,
    "Date": "Tue Feb 7 1967",
    "": 0,
    "Opponent": "San Francisco Warriors",
    "Tm": 126,
    "Opp": 123,
    "W": 50,
    "L": 8,
    "Streak": "W 3",
    "Notes": "at Pittsburgh PA"
  },
  {
    "G": 59,
    "Date": "Wed Feb 8 1967",
    "": 0,
    "Opponent": "Cincinnati Royals",
    "Tm": 118,
    "Opp": 106,
    "W": 51,
    "L": 8,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 60,
    "Date": "Fri Feb 10 1967",
    "": 0,
    "Opponent": "Los Angeles Lakers",
    "Tm": 148,
    "Opp": 131,
    "W": 52,
    "L": 8,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 61,
    "Date": "Sat Feb 11 1967",
    "": 0,
    "Opponent": "Baltimore Bullets",
    "Tm": 133,
    "Opp": 139,
    "W": 52,
    "L": 9,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 62,
    "Date": "Sun Feb 12 1967",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 112,
    "Opp": 113,
    "W": 52,
    "L": 10,
    "Streak": "L 2",
    "Notes": 0
  },
  {
    "G": 63,
    "Date": "Mon Feb 13 1967",
    "": 0,
    "Opponent": "Cincinnati Royals",
    "Tm": 131,
    "Opp": 123,
    "W": 53,
    "L": 10,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 64,
    "Date": "Wed Feb 15 1967",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 127,
    "Opp": 121,
    "W": 54,
    "L": 10,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 65,
    "Date": "Fri Feb 17 1967",
    "": 0,
    "Opponent": "Cincinnati Royals",
    "Tm": 127,
    "Opp": 118,
    "W": 55,
    "L": 10,
    "Streak": "W 3",
    "Notes": "at Cleveland OH"
  },
  {
    "G": 66,
    "Date": "Sun Feb 19 1967",
    "": 0,
    "Opponent": "St. Louis Hawks",
    "Tm": 123,
    "Opp": 122,
    "W": 56,
    "L": 10,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 67,
    "Date": "Fri Feb 24 1967",
    "": 0,
    "Opponent": "Baltimore Bullets",
    "Tm": 149,
    "Opp": 118,
    "W": 57,
    "L": 10,
    "Streak": "W 5",
    "Notes": "at Pittsburgh PA"
  },
  {
    "G": 68,
    "Date": "Tue Feb 28 1967",
    "": 0,
    "Opponent": "Cincinnati Royals",
    "Tm": 127,
    "Opp": 107,
    "W": 58,
    "L": 10,
    "Streak": "W 6",
    "Notes": "at Syracuse NY"
  },
  {
    "G": 69,
    "Date": "Wed Mar 1 1967",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 122,
    "Opp": 129,
    "W": 58,
    "L": 11,
    "Streak": "L 1",
    "Notes": "at Evansville IN"
  },
  {
    "G": 70,
    "Date": "Thu Mar 2 1967",
    "": 0,
    "Opponent": "San Francisco Warriors",
    "Tm": 136,
    "Opp": 128,
    "W": 59,
    "L": 11,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 71,
    "Date": "Fri Mar 3 1967",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 129,
    "Opp": 103,
    "W": 60,
    "L": 11,
    "Streak": "W 2",
    "Notes": "at Boston MA"
  },
  {
    "G": 72,
    "Date": "Sun Mar 5 1967",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 131,
    "Opp": 106,
    "W": 61,
    "L": 11,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 73,
    "Date": "Mon Mar 6 1967",
    "": 0,
    "Opponent": "Los Angeles Lakers",
    "Tm": 119,
    "Opp": 117,
    "W": 62,
    "L": 11,
    "Streak": "W 4",
    "Notes": "at Pittsburgh PA"
  },
  {
    "G": 74,
    "Date": "Wed Mar 8 1967",
    "": "OT",
    "Opponent": "Boston Celtics",
    "Tm": 115,
    "Opp": 113,
    "W": 63,
    "L": 11,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 75,
    "Date": "Sat Mar 11 1967",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 114,
    "Opp": 116,
    "W": 63,
    "L": 12,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 76,
    "Date": "Sun Mar 12 1967",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 131,
    "Opp": 120,
    "W": 64,
    "L": 12,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 77,
    "Date": "Tue Mar 14 1967",
    "": 0,
    "Opponent": "San Francisco Warriors",
    "Tm": 139,
    "Opp": 110,
    "W": 65,
    "L": 12,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 78,
    "Date": "Wed Mar 15 1967",
    "": 0,
    "Opponent": "Los Angeles Lakers",
    "Tm": 138,
    "Opp": 123,
    "W": 66,
    "L": 12,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 79,
    "Date": "Thu Mar 16 1967",
    "": 0,
    "Opponent": "San Francisco Warriors",
    "Tm": 131,
    "Opp": 145,
    "W": 66,
    "L": 13,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 80,
    "Date": "Sat Mar 18 1967",
    "": 0,
    "Opponent": "Baltimore Bullets",
    "Tm": 135,
    "Opp": 119,
    "W": 67,
    "L": 13,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 81,
    "Date": "Sun Mar 19 1967",
    "": 0,
    "Opponent": "Baltimore Bullets",
    "Tm": 132,
    "Opp": 129,
    "W": 68,
    "L": 13,
    "Streak": "W 2",
    "Notes": 0
  }
]