var _1996_bulls = [
  {
    "G": 1,
    "Date": "Fri Nov 3 1995",
    "": 0,
    "Opponent": "Charlotte Hornets",
    "Tm": 105,
    "Opp": 91,
    "W": 1,
    "L": 0,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 2,
    "Date": "Sat Nov 4 1995",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 107,
    "Opp": 85,
    "W": 2,
    "L": 0,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 3,
    "Date": "Tue Nov 7 1995",
    "": 0,
    "Opponent": "Toronto Raptors",
    "Tm": 117,
    "Opp": 108,
    "W": 3,
    "L": 0,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 4,
    "Date": "Thu Nov 9 1995",
    "": 0,
    "Opponent": "Cleveland Cavaliers",
    "Tm": 106,
    "Opp": 88,
    "W": 4,
    "L": 0,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 5,
    "Date": "Sat Nov 11 1995",
    "": 0,
    "Opponent": "Portland Trail Blazers",
    "Tm": 110,
    "Opp": 106,
    "W": 5,
    "L": 0,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 6,
    "Date": "Tue Nov 14 1995",
    "": 0,
    "Opponent": "Orlando Magic",
    "Tm": 88,
    "Opp": 94,
    "W": 5,
    "L": 1,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 7,
    "Date": "Wed Nov 15 1995",
    "": 0,
    "Opponent": "Cleveland Cavaliers",
    "Tm": 113,
    "Opp": 94,
    "W": 6,
    "L": 1,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 8,
    "Date": "Fri Nov 17 1995",
    "": 0,
    "Opponent": "New Jersey Nets",
    "Tm": 109,
    "Opp": 94,
    "W": 7,
    "L": 1,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 9,
    "Date": "Tue Nov 21 1995",
    "": "OT",
    "Opponent": "Dallas Mavericks",
    "Tm": 108,
    "Opp": 102,
    "W": 8,
    "L": 1,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 10,
    "Date": "Wed Nov 22 1995",
    "": 0,
    "Opponent": "San Antonio Spurs",
    "Tm": 103,
    "Opp": 94,
    "W": 9,
    "L": 1,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 11,
    "Date": "Fri Nov 24 1995",
    "": 0,
    "Opponent": "Utah Jazz",
    "Tm": 90,
    "Opp": 85,
    "W": 10,
    "L": 1,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 12,
    "Date": "Sun Nov 26 1995",
    "": 0,
    "Opponent": "Seattle SuperSonics",
    "Tm": 92,
    "Opp": 97,
    "W": 10,
    "L": 2,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 13,
    "Date": "Mon Nov 27 1995",
    "": 0,
    "Opponent": "Portland Trail Blazers",
    "Tm": 107,
    "Opp": 104,
    "W": 11,
    "L": 2,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 14,
    "Date": "Thu Nov 30 1995",
    "": 0,
    "Opponent": "Vancouver Grizzlies",
    "Tm": 94,
    "Opp": 88,
    "W": 12,
    "L": 2,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 15,
    "Date": "Sat Dec 2 1995",
    "": 0,
    "Opponent": "Los Angeles Clippers",
    "Tm": 104,
    "Opp": 98,
    "W": 13,
    "L": 2,
    "Streak": "W 3",
    "Notes": "at Anaheim CA"
  },
  {
    "G": 16,
    "Date": "Wed Dec 6 1995",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 101,
    "Opp": 94,
    "W": 14,
    "L": 2,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 17,
    "Date": "Fri Dec 8 1995",
    "": 0,
    "Opponent": "San Antonio Spurs",
    "Tm": 106,
    "Opp": 87,
    "W": 15,
    "L": 2,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 18,
    "Date": "Sat Dec 9 1995",
    "": 0,
    "Opponent": "Milwaukee Bucks",
    "Tm": 118,
    "Opp": 106,
    "W": 16,
    "L": 2,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 19,
    "Date": "Wed Dec 13 1995",
    "": 0,
    "Opponent": "Orlando Magic",
    "Tm": 112,
    "Opp": 103,
    "W": 17,
    "L": 2,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 20,
    "Date": "Thu Dec 14 1995",
    "": 0,
    "Opponent": "Atlanta Hawks",
    "Tm": 127,
    "Opp": 108,
    "W": 18,
    "L": 2,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 21,
    "Date": "Sat Dec 16 1995",
    "": 0,
    "Opponent": "Los Angeles Lakers",
    "Tm": 108,
    "Opp": 88,
    "W": 19,
    "L": 2,
    "Streak": "W 9",
    "Notes": 0
  },
  {
    "G": 22,
    "Date": "Mon Dec 18 1995",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 123,
    "Opp": 114,
    "W": 20,
    "L": 2,
    "Streak": "W 10",
    "Notes": 0
  },
  {
    "G": 23,
    "Date": "Tue Dec 19 1995",
    "": 0,
    "Opponent": "Dallas Mavericks",
    "Tm": 114,
    "Opp": 101,
    "W": 21,
    "L": 2,
    "Streak": "W 11",
    "Notes": 0
  },
  {
    "G": 24,
    "Date": "Fri Dec 22 1995",
    "": 0,
    "Opponent": "Toronto Raptors",
    "Tm": 113,
    "Opp": 104,
    "W": 22,
    "L": 2,
    "Streak": "W 12",
    "Notes": 0
  },
  {
    "G": 25,
    "Date": "Sat Dec 23 1995",
    "": 0,
    "Opponent": "Utah Jazz",
    "Tm": 100,
    "Opp": 86,
    "W": 23,
    "L": 2,
    "Streak": "W 13",
    "Notes": 0
  },
  {
    "G": 26,
    "Date": "Tue Dec 26 1995",
    "": 0,
    "Opponent": "Indiana Pacers",
    "Tm": 97,
    "Opp": 103,
    "W": 23,
    "L": 3,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 27,
    "Date": "Fri Dec 29 1995",
    "": 0,
    "Opponent": "Indiana Pacers",
    "Tm": 120,
    "Opp": 93,
    "W": 24,
    "L": 3,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 28,
    "Date": "Sat Dec 30 1995",
    "": 0,
    "Opponent": "Atlanta Hawks",
    "Tm": 95,
    "Opp": 93,
    "W": 25,
    "L": 3,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 29,
    "Date": "Wed Jan 3 1996",
    "": 0,
    "Opponent": "Houston Rockets",
    "Tm": 100,
    "Opp": 86,
    "W": 26,
    "L": 3,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 30,
    "Date": "Thu Jan 4 1996",
    "": 0,
    "Opponent": "Charlotte Hornets",
    "Tm": 117,
    "Opp": 93,
    "W": 27,
    "L": 3,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 31,
    "Date": "Sat Jan 6 1996",
    "": 0,
    "Opponent": "Milwaukee Bucks",
    "Tm": 113,
    "Opp": 84,
    "W": 28,
    "L": 3,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 32,
    "Date": "Wed Jan 10 1996",
    "": 0,
    "Opponent": "Seattle SuperSonics",
    "Tm": 113,
    "Opp": 87,
    "W": 29,
    "L": 3,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 33,
    "Date": "Sat Jan 13 1996",
    "": 0,
    "Opponent": "Philadelphia 76ers",
    "Tm": 120,
    "Opp": 93,
    "W": 30,
    "L": 3,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 34,
    "Date": "Mon Jan 15 1996",
    "": 0,
    "Opponent": "Washington Bullets",
    "Tm": 116,
    "Opp": 109,
    "W": 31,
    "L": 3,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 35,
    "Date": "Tue Jan 16 1996",
    "": 0,
    "Opponent": "Philadelphia 76ers",
    "Tm": 116,
    "Opp": 104,
    "W": 32,
    "L": 3,
    "Streak": "W 9",
    "Notes": 0
  },
  {
    "G": 36,
    "Date": "Thu Jan 18 1996",
    "": 0,
    "Opponent": "Toronto Raptors",
    "Tm": 92,
    "Opp": 89,
    "W": 33,
    "L": 3,
    "Streak": "W 10",
    "Notes": 0
  },
  {
    "G": 37,
    "Date": "Sun Jan 21 1996",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 111,
    "Opp": 96,
    "W": 34,
    "L": 3,
    "Streak": "W 11",
    "Notes": 0
  },
  {
    "G": 38,
    "Date": "Tue Jan 23 1996",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 99,
    "Opp": 79,
    "W": 35,
    "L": 3,
    "Streak": "W 12",
    "Notes": 0
  },
  {
    "G": 39,
    "Date": "Wed Jan 24 1996",
    "": 0,
    "Opponent": "Vancouver Grizzlies",
    "Tm": 104,
    "Opp": 84,
    "W": 36,
    "L": 3,
    "Streak": "W 13",
    "Notes": 0
  },
  {
    "G": 40,
    "Date": "Fri Jan 26 1996",
    "": 0,
    "Opponent": "Miami Heat",
    "Tm": 102,
    "Opp": 80,
    "W": 37,
    "L": 3,
    "Streak": "W 14",
    "Notes": 0
  },
  {
    "G": 41,
    "Date": "Sun Jan 28 1996",
    "": 0,
    "Opponent": "Phoenix Suns",
    "Tm": 93,
    "Opp": 82,
    "W": 38,
    "L": 3,
    "Streak": "W 15",
    "Notes": 0
  },
  {
    "G": 42,
    "Date": "Tue Jan 30 1996",
    "": 0,
    "Opponent": "Houston Rockets",
    "Tm": 98,
    "Opp": 87,
    "W": 39,
    "L": 3,
    "Streak": "W 16",
    "Notes": 0
  },
  {
    "G": 43,
    "Date": "Thu Feb 1 1996",
    "": 0,
    "Opponent": "Sacramento Kings",
    "Tm": 105,
    "Opp": 85,
    "W": 40,
    "L": 3,
    "Streak": "W 17",
    "Notes": 0
  },
  {
    "G": 44,
    "Date": "Fri Feb 2 1996",
    "": 0,
    "Opponent": "Los Angeles Lakers",
    "Tm": 99,
    "Opp": 84,
    "W": 41,
    "L": 3,
    "Streak": "W 18",
    "Notes": 0
  },
  {
    "G": 45,
    "Date": "Sun Feb 4 1996",
    "": 0,
    "Opponent": "Denver Nuggets",
    "Tm": 99,
    "Opp": 105,
    "W": 41,
    "L": 4,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 46,
    "Date": "Tue Feb 6 1996",
    "": 0,
    "Opponent": "Phoenix Suns",
    "Tm": 96,
    "Opp": 106,
    "W": 41,
    "L": 5,
    "Streak": "L 2",
    "Notes": 0
  },
  {
    "G": 47,
    "Date": "Wed Feb 7 1996",
    "": 0,
    "Opponent": "Golden State Warriors",
    "Tm": 99,
    "Opp": 95,
    "W": 42,
    "L": 5,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 48,
    "Date": "Tue Feb 13 1996",
    "": 0,
    "Opponent": "Washington Bullets",
    "Tm": 111,
    "Opp": 98,
    "W": 43,
    "L": 5,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 49,
    "Date": "Thu Feb 15 1996",
    "": "OT",
    "Opponent": "Detroit Pistons",
    "Tm": 112,
    "Opp": 109,
    "W": 44,
    "L": 5,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 50,
    "Date": "Fri Feb 16 1996",
    "": 0,
    "Opponent": "Minnesota Timberwolves",
    "Tm": 103,
    "Opp": 100,
    "W": 45,
    "L": 5,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 51,
    "Date": "Sun Feb 18 1996",
    "": 0,
    "Opponent": "Indiana Pacers",
    "Tm": 110,
    "Opp": 102,
    "W": 46,
    "L": 5,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 52,
    "Date": "Tue Feb 20 1996",
    "": 0,
    "Opponent": "Cleveland Cavaliers",
    "Tm": 102,
    "Opp": 76,
    "W": 47,
    "L": 5,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 53,
    "Date": "Thu Feb 22 1996",
    "": 0,
    "Opponent": "Atlanta Hawks",
    "Tm": 96,
    "Opp": 91,
    "W": 48,
    "L": 5,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 54,
    "Date": "Fri Feb 23 1996",
    "": 0,
    "Opponent": "Miami Heat",
    "Tm": 104,
    "Opp": 113,
    "W": 48,
    "L": 6,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 55,
    "Date": "Sun Feb 25 1996",
    "": 0,
    "Opponent": "Orlando Magic",
    "Tm": 111,
    "Opp": 91,
    "W": 49,
    "L": 6,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 56,
    "Date": "Tue Feb 27 1996",
    "": 0,
    "Opponent": "Minnesota Timberwolves",
    "Tm": 120,
    "Opp": 99,
    "W": 50,
    "L": 6,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 57,
    "Date": "Fri Mar 1 1996",
    "": 0,
    "Opponent": "Golden State Warriors",
    "Tm": 110,
    "Opp": 87,
    "W": 51,
    "L": 6,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 58,
    "Date": "Sat Mar 2 1996",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 107,
    "Opp": 75,
    "W": 52,
    "L": 6,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 59,
    "Date": "Tue Mar 5 1996",
    "": 0,
    "Opponent": "Milwaukee Bucks",
    "Tm": 115,
    "Opp": 106,
    "W": 53,
    "L": 6,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 60,
    "Date": "Thu Mar 7 1996",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 102,
    "Opp": 81,
    "W": 54,
    "L": 6,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 61,
    "Date": "Sun Mar 10 1996",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 72,
    "Opp": 104,
    "W": 54,
    "L": 7,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 62,
    "Date": "Wed Mar 13 1996",
    "": 0,
    "Opponent": "Washington Bullets",
    "Tm": 103,
    "Opp": 86,
    "W": 55,
    "L": 7,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 63,
    "Date": "Fri Mar 15 1996",
    "": 0,
    "Opponent": "Denver Nuggets",
    "Tm": 108,
    "Opp": 87,
    "W": 56,
    "L": 7,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 64,
    "Date": "Sat Mar 16 1996",
    "": 0,
    "Opponent": "New Jersey Nets",
    "Tm": 97,
    "Opp": 93,
    "W": 57,
    "L": 7,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 65,
    "Date": "Mon Mar 18 1996",
    "": 0,
    "Opponent": "Philadelphia 76ers",
    "Tm": 98,
    "Opp": 94,
    "W": 58,
    "L": 7,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 66,
    "Date": "Tue Mar 19 1996",
    "": 0,
    "Opponent": "Sacramento Kings",
    "Tm": 89,
    "Opp": 67,
    "W": 59,
    "L": 7,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 67,
    "Date": "Thu Mar 21 1996",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 107,
    "Opp": 86,
    "W": 60,
    "L": 7,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 68,
    "Date": "Sun Mar 24 1996",
    "": 0,
    "Opponent": "Toronto Raptors",
    "Tm": 108,
    "Opp": 109,
    "W": 60,
    "L": 8,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 69,
    "Date": "Thu Mar 28 1996",
    "": 0,
    "Opponent": "Atlanta Hawks",
    "Tm": 111,
    "Opp": 80,
    "W": 61,
    "L": 8,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 70,
    "Date": "Sat Mar 30 1996",
    "": 0,
    "Opponent": "Los Angeles Clippers",
    "Tm": 106,
    "Opp": 85,
    "W": 62,
    "L": 8,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 71,
    "Date": "Tue Apr 2 1996",
    "": 0,
    "Opponent": "Miami Heat",
    "Tm": 110,
    "Opp": 92,
    "W": 63,
    "L": 8,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 72,
    "Date": "Thu Apr 4 1996",
    "": 0,
    "Opponent": "Miami Heat",
    "Tm": 100,
    "Opp": 92,
    "W": 64,
    "L": 8,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 73,
    "Date": "Fri Apr 5 1996",
    "": 0,
    "Opponent": "Charlotte Hornets",
    "Tm": 126,
    "Opp": 92,
    "W": 65,
    "L": 8,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 74,
    "Date": "Sun Apr 7 1996",
    "": 0,
    "Opponent": "Orlando Magic",
    "Tm": 90,
    "Opp": 86,
    "W": 66,
    "L": 8,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 75,
    "Date": "Mon Apr 8 1996",
    "": 0,
    "Opponent": "Charlotte Hornets",
    "Tm": 97,
    "Opp": 98,
    "W": 66,
    "L": 9,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 76,
    "Date": "Thu Apr 11 1996",
    "": 0,
    "Opponent": "New Jersey Nets",
    "Tm": 113,
    "Opp": 100,
    "W": 67,
    "L": 9,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 77,
    "Date": "Fri Apr 12 1996",
    "": 0,
    "Opponent": "Philadelphia 76ers",
    "Tm": 112,
    "Opp": 82,
    "W": 68,
    "L": 9,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 78,
    "Date": "Sun Apr 14 1996",
    "": 0,
    "Opponent": "Cleveland Cavaliers",
    "Tm": 98,
    "Opp": 72,
    "W": 69,
    "L": 9,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 79,
    "Date": "Tue Apr 16 1996",
    "": 0,
    "Opponent": "Milwaukee Bucks",
    "Tm": 86,
    "Opp": 80,
    "W": 70,
    "L": 9,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 80,
    "Date": "Thu Apr 18 1996",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 110,
    "Opp": 79,
    "W": 71,
    "L": 9,
    "Streak": "W 5",
    "Notes": 0
  },

  {
    "G": 81,
    "Date": "Sat Apr 20 1996",
    "": 0,
    "Opponent": "Indiana Pacers",
    "Tm": 99,
    "Opp": 100,
    "W": 71,
    "L": 10,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 82,
    "Date": "Sun Apr 21 1996",
    "": 0,
    "Opponent": "Washington Bullets",
    "Tm": 103,
    "Opp": 93,
    "W": 72,
    "L": 10,
    "Streak": "W 1",
    "Notes": 0
  }
]