var _1997_bulls = [
  {
    "G": 1,
    "Date": "Fri Nov 1 1996",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 107,
    "Opp": 98,
    "W": 1,
    "L": 0,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 2,
    "Date": "Sat Nov 2 1996",
    "": 0,
    "Opponent": "Philadelphia 76ers",
    "Tm": 115,
    "Opp": 86,
    "W": 2,
    "L": 0,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 3,
    "Date": "Tue Nov 5 1996",
    "": 0,
    "Opponent": "Vancouver Grizzlies",
    "Tm": 96,
    "Opp": 73,
    "W": 3,
    "L": 0,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 4,
    "Date": "Wed Nov 6 1996",
    "": 0,
    "Opponent": "Miami Heat",
    "Tm": 106,
    "Opp": 100,
    "W": 4,
    "L": 0,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 5,
    "Date": "Fri Nov 8 1996",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 98,
    "Opp": 80,
    "W": 5,
    "L": 0,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 6,
    "Date": "Sat Nov 9 1996",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 104,
    "Opp": 92,
    "W": 6,
    "L": 0,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 7,
    "Date": "Mon Nov 11 1996",
    "": 0,
    "Opponent": "Phoenix Suns",
    "Tm": 97,
    "Opp": 79,
    "W": 7,
    "L": 0,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 8,
    "Date": "Wed Nov 13 1996",
    "": 0,
    "Opponent": "Miami Heat",
    "Tm": 103,
    "Opp": 71,
    "W": 8,
    "L": 0,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 9,
    "Date": "Fri Nov 15 1996",
    "": 0,
    "Opponent": "Charlotte Hornets",
    "Tm": 110,
    "Opp": 87,
    "W": 9,
    "L": 0,
    "Streak": "W 9",
    "Notes": 0
  },
  {
    "G": 10,
    "Date": "Sat Nov 16 1996",
    "": 0,
    "Opponent": "Atlanta Hawks",
    "Tm": 97,
    "Opp": 69,
    "W": 10,
    "L": 0,
    "Streak": "W 10",
    "Notes": 0
  },
  {
    "G": 11,
    "Date": "Wed Nov 20 1996",
    "": 0,
    "Opponent": "Phoenix Suns",
    "Tm": 113,
    "Opp": 99,
    "W": 11,
    "L": 0,
    "Streak": "W 11",
    "Notes": 0
  },
  {
    "G": 12,
    "Date": "Thu Nov 21 1996",
    "": 0,
    "Opponent": "Denver Nuggets",
    "Tm": 110,
    "Opp": 92,
    "W": 12,
    "L": 0,
    "Streak": "W 12",
    "Notes": 0
  },
  {
    "G": 13,
    "Date": "Sat Nov 23 1996",
    "": 0,
    "Opponent": "Utah Jazz",
    "Tm": 100,
    "Opp": 105,
    "W": 12,
    "L": 1,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 14,
    "Date": "Mon Nov 25 1996",
    "": 0,
    "Opponent": "Los Angeles Clippers",
    "Tm": 88,
    "Opp": 84,
    "W": 13,
    "L": 1,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 15,
    "Date": "Fri Nov 29 1996",
    "": 0,
    "Opponent": "Dallas Mavericks",
    "Tm": 116,
    "Opp": 97,
    "W": 14,
    "L": 1,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 16,
    "Date": "Sat Nov 30 1996",
    "": 0,
    "Opponent": "San Antonio Spurs",
    "Tm": 97,
    "Opp": 88,
    "W": 15,
    "L": 1,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 17,
    "Date": "Tue Dec 3 1996",
    "": 0,
    "Opponent": "Milwaukee Bucks",
    "Tm": 107,
    "Opp": 104,
    "W": 16,
    "L": 1,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 18,
    "Date": "Thu Dec 5 1996",
    "": 0,
    "Opponent": "Los Angeles Clippers",
    "Tm": 114,
    "Opp": 96,
    "W": 17,
    "L": 1,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 19,
    "Date": "Sat Dec 7 1996",
    "": 0,
    "Opponent": "Miami Heat",
    "Tm": 80,
    "Opp": 83,
    "W": 17,
    "L": 2,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 20,
    "Date": "Sun Dec 8 1996",
    "": 0,
    "Opponent": "Toronto Raptors",
    "Tm": 89,
    "Opp": 97,
    "W": 17,
    "L": 3,
    "Streak": "L 2",
    "Notes": 0
  },
  {
    "G": 21,
    "Date": "Wed Dec 11 1996",
    "": 0,
    "Opponent": "Minnesota Timberwolves",
    "Tm": 103,
    "Opp": 86,
    "W": 18,
    "L": 3,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 22,
    "Date": "Fri Dec 13 1996",
    "": 0,
    "Opponent": "New Jersey Nets",
    "Tm": 113,
    "Opp": 92,
    "W": 19,
    "L": 3,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 23,
    "Date": "Sat Dec 14 1996",
    "": 0,
    "Opponent": "Charlotte Hornets",
    "Tm": 87,
    "Opp": 82,
    "W": 20,
    "L": 3,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 24,
    "Date": "Tue Dec 17 1996",
    "": "OT",
    "Opponent": "Los Angeles Lakers",
    "Tm": 129,
    "Opp": 123,
    "W": 21,
    "L": 3,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 25,
    "Date": "Thu Dec 19 1996",
    "": 0,
    "Opponent": "Charlotte Hornets",
    "Tm": 93,
    "Opp": 72,
    "W": 22,
    "L": 3,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 26,
    "Date": "Sat Dec 21 1996",
    "": 0,
    "Opponent": "Philadelphia 76ers",
    "Tm": 111,
    "Opp": 105,
    "W": 23,
    "L": 3,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 27,
    "Date": "Mon Dec 23 1996",
    "": 0,
    "Opponent": "New Jersey Nets",
    "Tm": 113,
    "Opp": 81,
    "W": 24,
    "L": 3,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 28,
    "Date": "Wed Dec 25 1996",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 95,
    "Opp": 83,
    "W": 25,
    "L": 3,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 29,
    "Date": "Thu Dec 26 1996",
    "": 0,
    "Opponent": "Atlanta Hawks",
    "Tm": 103,
    "Opp": 108,
    "W": 25,
    "L": 4,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 30,
    "Date": "Sat Dec 28 1996",
    "": 0,
    "Opponent": "Cleveland Cavaliers",
    "Tm": 102,
    "Opp": 97,
    "W": 26,
    "L": 4,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 31,
    "Date": "Mon Dec 30 1996",
    "": 0,
    "Opponent": "Indiana Pacers",
    "Tm": 81,
    "Opp": 79,
    "W": 27,
    "L": 4,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 32,
    "Date": "Fri Jan 3 1997",
    "": 0,
    "Opponent": "Orlando Magic",
    "Tm": 110,
    "Opp": 89,
    "W": 28,
    "L": 4,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 33,
    "Date": "Mon Jan 6 1997",
    "": 0,
    "Opponent": "Utah Jazz",
    "Tm": 102,
    "Opp": 89,
    "W": 29,
    "L": 4,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 34,
    "Date": "Fri Jan 10 1997",
    "": 0,
    "Opponent": "Milwaukee Bucks",
    "Tm": 116,
    "Opp": 101,
    "W": 30,
    "L": 4,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 35,
    "Date": "Sat Jan 11 1997",
    "": 0,
    "Opponent": "Houston Rockets",
    "Tm": 110,
    "Opp": 86,
    "W": 31,
    "L": 4,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 36,
    "Date": "Tue Jan 14 1997",
    "": 0,
    "Opponent": "Washington Bullets",
    "Tm": 108,
    "Opp": 107,
    "W": 32,
    "L": 4,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 37,
    "Date": "Wed Jan 15 1997",
    "": 0,
    "Opponent": "Minnesota Timberwolves",
    "Tm": 112,
    "Opp": 102,
    "W": 33,
    "L": 4,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 38,
    "Date": "Fri Jan 17 1997",
    "": 0,
    "Opponent": "Milwaukee Bucks",
    "Tm": 100,
    "Opp": 73,
    "W": 34,
    "L": 4,
    "Streak": "W 9",
    "Notes": 0
  },
  {
    "G": 39,
    "Date": "Sun Jan 19 1997",
    "": 0,
    "Opponent": "Houston Rockets",
    "Tm": 86,
    "Opp": 102,
    "W": 34,
    "L": 5,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 40,
    "Date": "Tue Jan 21 1997",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 88,
    "Opp": 87,
    "W": 35,
    "L": 5,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 41,
    "Date": "Thu Jan 23 1997",
    "": 0,
    "Opponent": "Cleveland Cavaliers",
    "Tm": 87,
    "Opp": 71,
    "W": 36,
    "L": 5,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 42,
    "Date": "Sat Jan 25 1997",
    "": 0,
    "Opponent": "Toronto Raptors",
    "Tm": 110,
    "Opp": 98,
    "W": 37,
    "L": 5,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 43,
    "Date": "Tue Jan 28 1997",
    "": 0,
    "Opponent": "Vancouver Grizzlies",
    "Tm": 111,
    "Opp": 96,
    "W": 38,
    "L": 5,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 44,
    "Date": "Thu Jan 30 1997",
    "": 0,
    "Opponent": "Sacramento Kings",
    "Tm": 111,
    "Opp": 93,
    "W": 39,
    "L": 5,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 45,
    "Date": "Fri Jan 31 1997",
    "": 0,
    "Opponent": "Golden State Warriors",
    "Tm": 115,
    "Opp": 92,
    "W": 40,
    "L": 5,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 46,
    "Date": "Sun Feb 2 1997",
    "": 0,
    "Opponent": "Seattle SuperSonics",
    "Tm": 91,
    "Opp": 84,
    "W": 41,
    "L": 5,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 47,
    "Date": "Tue Feb 4 1997",
    "": 0,
    "Opponent": "Portland Trail Blazers",
    "Tm": 88,
    "Opp": 84,
    "W": 42,
    "L": 5,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 48,
    "Date": "Wed Feb 5 1997",
    "": 0,
    "Opponent": "Los Angeles Lakers",
    "Tm": 90,
    "Opp": 106,
    "W": 42,
    "L": 6,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 49,
    "Date": "Tue Feb 11 1997",
    "": 0,
    "Opponent": "Charlotte Hornets",
    "Tm": 103,
    "Opp": 100,
    "W": 43,
    "L": 6,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 50,
    "Date": "Fri Feb 14 1997",
    "": 0,
    "Opponent": "Atlanta Hawks",
    "Tm": 89,
    "Opp": 88,
    "W": 44,
    "L": 6,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 51,
    "Date": "Sun Feb 16 1997",
    "": 0,
    "Opponent": "Orlando Magic",
    "Tm": 110,
    "Opp": 89,
    "W": 45,
    "L": 6,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 52,
    "Date": "Tue Feb 18 1997",
    "": 0,
    "Opponent": "Denver Nuggets",
    "Tm": 134,
    "Opp": 123,
    "W": 46,
    "L": 6,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 53,
    "Date": "Fri Feb 21 1997",
    "": 0,
    "Opponent": "Washington Bullets",
    "Tm": 103,
    "Opp": 99,
    "W": 47,
    "L": 6,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 54,
    "Date": "Sat Feb 22 1997",
    "": 0,
    "Opponent": "Golden State Warriors",
    "Tm": 120,
    "Opp": 87,
    "W": 48,
    "L": 6,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 55,
    "Date": "Mon Feb 24 1997",
    "": 0,
    "Opponent": "Portland Trail Blazers",
    "Tm": 116,
    "Opp": 89,
    "W": 49,
    "L": 6,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 56,
    "Date": "Thu Feb 27 1997",
    "": 0,
    "Opponent": "Cleveland Cavaliers",
    "Tm": 70,
    "Opp": 73,
    "W": 49,
    "L": 7,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 57,
    "Date": "Fri Feb 28 1997",
    "": 0,
    "Opponent": "Sacramento Kings",
    "Tm": 126,
    "Opp": 108,
    "W": 50,
    "L": 7,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 58,
    "Date": "Mon Mar 3 1997",
    "": 0,
    "Opponent": "Milwaukee Bucks",
    "Tm": 108,
    "Opp": 90,
    "W": 51,
    "L": 7,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 59,
    "Date": "Wed Mar 5 1997",
    "": 0,
    "Opponent": "San Antonio Spurs",
    "Tm": 111,
    "Opp": 69,
    "W": 52,
    "L": 7,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 60,
    "Date": "Fri Mar 7 1997",
    "": 0,
    "Opponent": "Indiana Pacers",
    "Tm": 104,
    "Opp": 96,
    "W": 53,
    "L": 7,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 61,
    "Date": "Sun Mar 9 1997",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 93,
    "Opp": 97,
    "W": 53,
    "L": 8,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 62,
    "Date": "Tue Mar 11 1997",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 117,
    "Opp": 106,
    "W": 54,
    "L": 8,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 63,
    "Date": "Wed Mar 12 1997",
    "": 0,
    "Opponent": "Philadelphia 76ers",
    "Tm": 108,
    "Opp": 104,
    "W": 55,
    "L": 8,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 64,
    "Date": "Fri Mar 14 1997",
    "": 0,
    "Opponent": "New Jersey Nets",
    "Tm": 98,
    "Opp": 99,
    "W": 55,
    "L": 9,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 65,
    "Date": "Sat Mar 15 1997",
    "": 0,
    "Opponent": "Atlanta Hawks",
    "Tm": 99,
    "Opp": 79,
    "W": 56,
    "L": 9,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 66,
    "Date": "Tue Mar 18 1997",
    "": "OT",
    "Opponent": "Seattle SuperSonics",
    "Tm": 89,
    "Opp": 87,
    "W": 57,
    "L": 9,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 67,
    "Date": "Fri Mar 21 1997",
    "": 0,
    "Opponent": "Indiana Pacers",
    "Tm": 117,
    "Opp": 98,
    "W": 58,
    "L": 9,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 68,
    "Date": "Sat Mar 22 1997",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 103,
    "Opp": 88,
    "W": 59,
    "L": 9,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 69,
    "Date": "Tue Mar 25 1997",
    "": 0,
    "Opponent": "Dallas Mavericks",
    "Tm": 94,
    "Opp": 92,
    "W": 60,
    "L": 9,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 70,
    "Date": "Thu Mar 27 1997",
    "": 0,
    "Opponent": "Toronto Raptors",
    "Tm": 96,
    "Opp": 83,
    "W": 61,
    "L": 9,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 71,
    "Date": "Sat Mar 29 1997",
    "": 0,
    "Opponent": "New Jersey Nets",
    "Tm": 111,
    "Opp": 101,
    "W": 62,
    "L": 9,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 72,
    "Date": "Tue Apr 1 1997",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 111,
    "Opp": 106,
    "W": 63,
    "L": 9,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 73,
    "Date": "Thu Apr 3 1997",
    "": 0,
    "Opponent": "Washington Bullets",
    "Tm": 102,
    "Opp": 110,
    "W": 63,
    "L": 10,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 74,
    "Date": "Fri Apr 4 1997",
    "": 0,
    "Opponent": "Cleveland Cavaliers",
    "Tm": 84,
    "Opp": 71,
    "W": 64,
    "L": 10,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 75,
    "Date": "Sun Apr 6 1997",
    "": 0,
    "Opponent": "Orlando Magic",
    "Tm": 110,
    "Opp": 94,
    "W": 65,
    "L": 10,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 76,
    "Date": "Mon Apr 7 1997",
    "": 0,
    "Opponent": "Philadelphia 76ers",
    "Tm": 128,
    "Opp": 102,
    "W": 66,
    "L": 10,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 77,
    "Date": "Wed Apr 9 1997",
    "": 0,
    "Opponent": "Indiana Pacers",
    "Tm": 86,
    "Opp": 80,
    "W": 67,
    "L": 10,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 78,
    "Date": "Thu Apr 10 1997",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 105,
    "Opp": 103,
    "W": 68,
    "L": 10,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 79,
    "Date": "Sun Apr 13 1997",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 91,
    "Opp": 108,
    "W": 68,
    "L": 11,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 80,
    "Date": "Mon Apr 14 1997",
    "": 0,
    "Opponent": "Toronto Raptors",
    "Tm": 117,
    "Opp": 100,
    "W": 69,
    "L": 11,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 81,
    "Date": "Wed Apr 16 1997",
    "": 0,
    "Opponent": "Miami Heat",
    "Tm": 92,
    "Opp": 102,
    "W": 69,
    "L": 12,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 82,
    "Date": "Sat Apr 19 1997",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 101,
    "Opp": 103,
    "W": 69,
    "L": 13,
    "Streak": "L 2",
    "Notes": 0
  }
]