var _2000_lakers = [
  {
    "G": 1,
    "Date": "Tue Nov 2 1999",
    "": 0,
    "Opponent": "Utah Jazz",
    "Tm": 91,
    "Opp": 84,
    "W": 1,
    "L": 0,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 2,
    "Date": "Wed Nov 3 1999",
    "": 0,
    "Opponent": "Vancouver Grizzlies",
    "Tm": 103,
    "Opp": 88,
    "W": 2,
    "L": 0,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 3,
    "Date": "Sat Nov 6 1999",
    "": 0,
    "Opponent": "Portland Trail Blazers",
    "Tm": 82,
    "Opp": 97,
    "W": 2,
    "L": 1,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 4,
    "Date": "Sun Nov 7 1999",
    "": 0,
    "Opponent": "Dallas Mavericks",
    "Tm": 105,
    "Opp": 97,
    "W": 3,
    "L": 1,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 5,
    "Date": "Tue Nov 9 1999",
    "": 0,
    "Opponent": "Dallas Mavericks",
    "Tm": 123,
    "Opp": 101,
    "W": 4,
    "L": 1,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 6,
    "Date": "Wed Nov 10 1999",
    "": 0,
    "Opponent": "Houston Rockets",
    "Tm": 89,
    "Opp": 88,
    "W": 5,
    "L": 1,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 7,
    "Date": "Fri Nov 12 1999",
    "": 0,
    "Opponent": "Houston Rockets",
    "Tm": 81,
    "Opp": 97,
    "W": 5,
    "L": 2,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 8,
    "Date": "Sun Nov 14 1999",
    "": 0,
    "Opponent": "Atlanta Hawks",
    "Tm": 93,
    "Opp": 88,
    "W": 6,
    "L": 2,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 9,
    "Date": "Mon Nov 15 1999",
    "": 0,
    "Opponent": "Phoenix Suns",
    "Tm": 91,
    "Opp": 82,
    "W": 7,
    "L": 2,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 10,
    "Date": "Thu Nov 18 1999",
    "": 0,
    "Opponent": "Denver Nuggets",
    "Tm": 82,
    "Opp": 93,
    "W": 7,
    "L": 3,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 11,
    "Date": "Fri Nov 19 1999",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 103,
    "Opp": 95,
    "W": 8,
    "L": 3,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 12,
    "Date": "Sun Nov 21 1999",
    "": 0,
    "Opponent": "Toronto Raptors",
    "Tm": 102,
    "Opp": 111,
    "W": 8,
    "L": 4,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 13,
    "Date": "Wed Nov 24 1999",
    "": 0,
    "Opponent": "Utah Jazz",
    "Tm": 90,
    "Opp": 82,
    "W": 9,
    "L": 4,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 14,
    "Date": "Fri Nov 26 1999",
    "": 0,
    "Opponent": "New Jersey Nets",
    "Tm": 103,
    "Opp": 80,
    "W": 10,
    "L": 4,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 15,
    "Date": "Tue Nov 30 1999",
    "": 0,
    "Opponent": "Seattle SuperSonics",
    "Tm": 101,
    "Opp": 77,
    "W": 11,
    "L": 4,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 16,
    "Date": "Wed Dec 1 1999",
    "": 0,
    "Opponent": "Golden State Warriors",
    "Tm": 93,
    "Opp": 75,
    "W": 12,
    "L": 4,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 17,
    "Date": "Fri Dec 3 1999",
    "": 0,
    "Opponent": "Portland Trail Blazers",
    "Tm": 93,
    "Opp": 80,
    "W": 13,
    "L": 4,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 18,
    "Date": "Sun Dec 5 1999",
    "": 0,
    "Opponent": "Orlando Magic",
    "Tm": 117,
    "Opp": 100,
    "W": 14,
    "L": 4,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 19,
    "Date": "Tue Dec 7 1999",
    "": 0,
    "Opponent": "Washington Wizards",
    "Tm": 91,
    "Opp": 80,
    "W": 15,
    "L": 4,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 20,
    "Date": "Wed Dec 8 1999",
    "": 0,
    "Opponent": "Sacramento Kings",
    "Tm": 91,
    "Opp": 103,
    "W": 15,
    "L": 5,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 21,
    "Date": "Sat Dec 11 1999",
    "": 0,
    "Opponent": "Vancouver Grizzlies",
    "Tm": 106,
    "Opp": 94,
    "W": 16,
    "L": 5,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 22,
    "Date": "Sun Dec 12 1999",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 101,
    "Opp": 93,
    "W": 17,
    "L": 5,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 23,
    "Date": "Tue Dec 14 1999",
    "": 0,
    "Opponent": "Los Angeles Clippers",
    "Tm": 95,
    "Opp": 68,
    "W": 18,
    "L": 5,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 24,
    "Date": "Thu Dec 16 1999",
    "": 0,
    "Opponent": "Atlanta Hawks",
    "Tm": 95,
    "Opp": 88,
    "W": 19,
    "L": 5,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 25,
    "Date": "Fri Dec 17 1999",
    "": 0,
    "Opponent": "Minnesota Timberwolves",
    "Tm": 97,
    "Opp": 88,
    "W": 20,
    "L": 5,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 26,
    "Date": "Sun Dec 19 1999",
    "": 0,
    "Opponent": "Toronto Raptors",
    "Tm": 94,
    "Opp": 88,
    "W": 21,
    "L": 5,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 27,
    "Date": "Mon Dec 20 1999",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 99,
    "Opp": 90,
    "W": 22,
    "L": 5,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 28,
    "Date": "Sat Dec 25 1999",
    "": 0,
    "Opponent": "San Antonio Spurs",
    "Tm": 99,
    "Opp": 93,
    "W": 23,
    "L": 5,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 29,
    "Date": "Mon Dec 27 1999",
    "": 0,
    "Opponent": "Dallas Mavericks",
    "Tm": 108,
    "Opp": 106,
    "W": 24,
    "L": 5,
    "Streak": "W 9",
    "Notes": 0
  },
  {
    "G": 30,
    "Date": "Wed Dec 29 1999",
    "": 0,
    "Opponent": "Phoenix Suns",
    "Tm": 103,
    "Opp": 87,
    "W": 25,
    "L": 5,
    "Streak": "W 10",
    "Notes": 0
  },
  {
    "G": 31,
    "Date": "Tue Jan 4 2000",
    "": 0,
    "Opponent": "Los Angeles Clippers",
    "Tm": 122,
    "Opp": 98,
    "W": 26,
    "L": 5,
    "Streak": "W 11",
    "Notes": 0
  },
  {
    "G": 32,
    "Date": "Wed Jan 5 2000",
    "": 0,
    "Opponent": "Los Angeles Clippers",
    "Tm": 118,
    "Opp": 101,
    "W": 27,
    "L": 5,
    "Streak": "W 12",
    "Notes": 0
  },
  {
    "G": 33,
    "Date": "Fri Jan 7 2000",
    "": 0,
    "Opponent": "Charlotte Hornets",
    "Tm": 87,
    "Opp": 83,
    "W": 28,
    "L": 5,
    "Streak": "W 13",
    "Notes": 0
  },
  {
    "G": 34,
    "Date": "Sat Jan 8 2000",
    "": 0,
    "Opponent": "Seattle SuperSonics",
    "Tm": 110,
    "Opp": 100,
    "W": 29,
    "L": 5,
    "Streak": "W 14",
    "Notes": 0
  },
  {
    "G": 35,
    "Date": "Mon Jan 10 2000",
    "": 0,
    "Opponent": "Denver Nuggets",
    "Tm": 130,
    "Opp": 95,
    "W": 30,
    "L": 5,
    "Streak": "W 15",
    "Notes": 0
  },
  {
    "G": 36,
    "Date": "Wed Jan 12 2000",
    "": 0,
    "Opponent": "Milwaukee Bucks",
    "Tm": 103,
    "Opp": 94,
    "W": 31,
    "L": 5,
    "Streak": "W 16",
    "Notes": 0
  },
  {
    "G": 37,
    "Date": "Fri Jan 14 2000",
    "": 0,
    "Opponent": "Indiana Pacers",
    "Tm": 102,
    "Opp": 111,
    "W": 31,
    "L": 6,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 38,
    "Date": "Sat Jan 15 2000",
    "": 0,
    "Opponent": "Minnesota Timberwolves",
    "Tm": 104,
    "Opp": 91,
    "W": 32,
    "L": 6,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 39,
    "Date": "Mon Jan 17 2000",
    "": 0,
    "Opponent": "Seattle SuperSonics",
    "Tm": 81,
    "Opp": 82,
    "W": 32,
    "L": 7,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 40,
    "Date": "Wed Jan 19 2000",
    "": 0,
    "Opponent": "Cleveland Cavaliers",
    "Tm": 95,
    "Opp": 86,
    "W": 33,
    "L": 7,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 41,
    "Date": "Sat Jan 22 2000",
    "": 0,
    "Opponent": "Portland Trail Blazers",
    "Tm": 91,
    "Opp": 95,
    "W": 33,
    "L": 8,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 42,
    "Date": "Mon Jan 24 2000",
    "": "2OT",
    "Opponent": "Utah Jazz",
    "Tm": 101,
    "Opp": 105,
    "W": 33,
    "L": 9,
    "Streak": "L 2",
    "Notes": 0
  },
  {
    "G": 43,
    "Date": "Fri Jan 28 2000",
    "": 0,
    "Opponent": "Milwaukee Bucks",
    "Tm": 117,
    "Opp": 89,
    "W": 34,
    "L": 9,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 44,
    "Date": "Sun Jan 30 2000",
    "": 0,
    "Opponent": "Houston Rockets",
    "Tm": 83,
    "Opp": 89,
    "W": 34,
    "L": 10,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 45,
    "Date": "Tue Feb 1 2000",
    "": 0,
    "Opponent": "San Antonio Spurs",
    "Tm": 81,
    "Opp": 105,
    "W": 34,
    "L": 11,
    "Streak": "L 2",
    "Notes": 0
  },
  {
    "G": 46,
    "Date": "Fri Feb 4 2000",
    "": 0,
    "Opponent": "Utah Jazz",
    "Tm": 113,
    "Opp": 67,
    "W": 35,
    "L": 11,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 47,
    "Date": "Mon Feb 7 2000",
    "": 0,
    "Opponent": "Denver Nuggets",
    "Tm": 106,
    "Opp": 98,
    "W": 36,
    "L": 11,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 48,
    "Date": "Wed Feb 9 2000",
    "": 0,
    "Opponent": "Minnesota Timberwolves",
    "Tm": 114,
    "Opp": 81,
    "W": 37,
    "L": 11,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 49,
    "Date": "Tue Feb 15 2000",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 88,
    "Opp": 76,
    "W": 38,
    "L": 11,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 50,
    "Date": "Wed Feb 16 2000",
    "": 0,
    "Opponent": "Charlotte Hornets",
    "Tm": 92,
    "Opp": 85,
    "W": 39,
    "L": 11,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 51,
    "Date": "Fri Feb 18 2000",
    "": "OT",
    "Opponent": "Orlando Magic",
    "Tm": 107,
    "Opp": 99,
    "W": 40,
    "L": 11,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 52,
    "Date": "Sun Feb 20 2000",
    "": 0,
    "Opponent": "Philadelphia 76ers",
    "Tm": 87,
    "Opp": 84,
    "W": 41,
    "L": 11,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 53,
    "Date": "Tue Feb 22 2000",
    "": 0,
    "Opponent": "New Jersey Nets",
    "Tm": 97,
    "Opp": 89,
    "W": 42,
    "L": 11,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 54,
    "Date": "Wed Feb 23 2000",
    "": 0,
    "Opponent": "Cleveland Cavaliers",
    "Tm": 116,
    "Opp": 98,
    "W": 43,
    "L": 11,
    "Streak": "W 9",
    "Notes": 0
  },
  {
    "G": 55,
    "Date": "Fri Feb 25 2000",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 109,
    "Opp": 96,
    "W": 44,
    "L": 11,
    "Streak": "W 10",
    "Notes": 0
  },
  {
    "G": 56,
    "Date": "Sun Feb 27 2000",
    "": 0,
    "Opponent": "Houston Rockets",
    "Tm": 101,
    "Opp": 85,
    "W": 45,
    "L": 11,
    "Streak": "W 11",
    "Notes": 0
  },
  {
    "G": 57,
    "Date": "Tue Feb 29 2000",
    "": 0,
    "Opponent": "Portland Trail Blazers",
    "Tm": 90,
    "Opp": 87,
    "W": 46,
    "L": 11,
    "Streak": "W 12",
    "Notes": 0
  },
  {
    "G": 58,
    "Date": "Wed Mar 1 2000",
    "": 0,
    "Opponent": "Vancouver Grizzlies",
    "Tm": 103,
    "Opp": 91,
    "W": 47,
    "L": 11,
    "Streak": "W 13",
    "Notes": 0
  },
  {
    "G": 59,
    "Date": "Fri Mar 3 2000",
    "": 0,
    "Opponent": "Indiana Pacers",
    "Tm": 107,
    "Opp": 92,
    "W": 48,
    "L": 11,
    "Streak": "W 14",
    "Notes": 0
  },
  {
    "G": 60,
    "Date": "Sun Mar 5 2000",
    "": 0,
    "Opponent": "Miami Heat",
    "Tm": 93,
    "Opp": 80,
    "W": 49,
    "L": 11,
    "Streak": "W 15",
    "Notes": 0
  },
  {
    "G": 61,
    "Date": "Mon Mar 6 2000",
    "": 0,
    "Opponent": "Los Angeles Clippers",
    "Tm": 123,
    "Opp": 103,
    "W": 50,
    "L": 11,
    "Streak": "W 16",
    "Notes": 0
  },
  {
    "G": 62,
    "Date": "Thu Mar 9 2000",
    "": 0,
    "Opponent": "Golden State Warriors",
    "Tm": 109,
    "Opp": 92,
    "W": 51,
    "L": 11,
    "Streak": "W 17",
    "Notes": 0
  },
  {
    "G": 63,
    "Date": "Sun Mar 12 2000",
    "": 0,
    "Opponent": "Sacramento Kings",
    "Tm": 109,
    "Opp": 106,
    "W": 52,
    "L": 11,
    "Streak": "W 18",
    "Notes": 0
  },
  {
    "G": 64,
    "Date": "Mon Mar 13 2000",
    "": 0,
    "Opponent": "Denver Nuggets",
    "Tm": 118,
    "Opp": 108,
    "W": 53,
    "L": 11,
    "Streak": "W 19",
    "Notes": 0
  },
  {
    "G": 65,
    "Date": "Thu Mar 16 2000",
    "": 0,
    "Opponent": "Washington Wizards",
    "Tm": 102,
    "Opp": 109,
    "W": 53,
    "L": 12,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 66,
    "Date": "Fri Mar 17 2000",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 110,
    "Opp": 82,
    "W": 54,
    "L": 12,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 67,
    "Date": "Sun Mar 19 2000",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 92,
    "Opp": 85,
    "W": 55,
    "L": 12,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 68,
    "Date": "Mon Mar 20 2000",
    "": 0,
    "Opponent": "Miami Heat",
    "Tm": 100,
    "Opp": 89,
    "W": 56,
    "L": 12,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 69,
    "Date": "Wed Mar 22 2000",
    "": 0,
    "Opponent": "Golden State Warriors",
    "Tm": 119,
    "Opp": 96,
    "W": 57,
    "L": 12,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 70,
    "Date": "Fri Mar 24 2000",
    "": 0,
    "Opponent": "Phoenix Suns",
    "Tm": 109,
    "Opp": 101,
    "W": 58,
    "L": 12,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 71,
    "Date": "Sun Mar 26 2000",
    "": 0,
    "Opponent": "Sacramento Kings",
    "Tm": 90,
    "Opp": 89,
    "W": 59,
    "L": 12,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 72,
    "Date": "Wed Mar 29 2000",
    "": 0,
    "Opponent": "Vancouver Grizzlies",
    "Tm": 108,
    "Opp": 99,
    "W": 60,
    "L": 12,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 73,
    "Date": "Fri Mar 31 2000",
    "": 0,
    "Opponent": "Philadelphia 76ers",
    "Tm": 100,
    "Opp": 88,
    "W": 61,
    "L": 12,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 74,
    "Date": "Sun Apr 2 2000",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 106,
    "Opp": 82,
    "W": 62,
    "L": 12,
    "Streak": "W 9",
    "Notes": 0
  },
  {
    "G": 75,
    "Date": "Tue Apr 4 2000",
    "": 0,
    "Opponent": "Phoenix Suns",
    "Tm": 84,
    "Opp": 83,
    "W": 63,
    "L": 12,
    "Streak": "W 10",
    "Notes": 0
  },
  {
    "G": 76,
    "Date": "Wed Apr 5 2000",
    "": 0,
    "Opponent": "Golden State Warriors",
    "Tm": 111,
    "Opp": 104,
    "W": 64,
    "L": 12,
    "Streak": "W 11",
    "Notes": 0
  },
  {
    "G": 77,
    "Date": "Sat Apr 8 2000",
    "": 0,
    "Opponent": "San Antonio Spurs",
    "Tm": 80,
    "Opp": 98,
    "W": 64,
    "L": 13,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 78,
    "Date": "Mon Apr 10 2000",
    "": "OT",
    "Opponent": "Seattle SuperSonics",
    "Tm": 106,
    "Opp": 103,
    "W": 65,
    "L": 13,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 79,
    "Date": "Fri Apr 14 2000",
    "": 0,
    "Opponent": "Sacramento Kings",
    "Tm": 121,
    "Opp": 114,
    "W": 66,
    "L": 13,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 80,
    "Date": "Sun Apr 16 2000",
    "": 0,
    "Opponent": "Minnesota Timberwolves",
    "Tm": 101,
    "Opp": 95,
    "W": 67,
    "L": 13,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 81,
    "Date": "Tue Apr 18 2000",
    "": 0,
    "Opponent": "Dallas Mavericks",
    "Tm": 102,
    "Opp": 112,
    "W": 67,
    "L": 14,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 82,
    "Date": "Wed Apr 19 2000",
    "": "OT",
    "Opponent": "San Antonio Spurs",
    "Tm": 98,
    "Opp": 103,
    "W": 67,
    "L": 15,
    "Streak": "L 2",
    "Notes": 0
  }
]