var _2006_pistons = [
  {
    "G": 1,
    "Date": "Wed Nov 2 2005",
    "": 0,
    "Opponent": "Philadelphia 76ers",
    "Tm": 108,
    "Opp": 88,
    "W": 1,
    "L": 0,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 2,
    "Date": "Fri Nov 4 2005",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 82,
    "Opp": 81,
    "W": 2,
    "L": 0,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 3,
    "Date": "Sat Nov 5 2005",
    "": 0,
    "Opponent": "Toronto Raptors",
    "Tm": 117,
    "Opp": 84,
    "W": 3,
    "L": 0,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 4,
    "Date": "Tue Nov 8 2005",
    "": 0,
    "Opponent": "Sacramento Kings",
    "Tm": 102,
    "Opp": 88,
    "W": 4,
    "L": 0,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 5,
    "Date": "Thu Nov 10 2005",
    "": 0,
    "Opponent": "Phoenix Suns",
    "Tm": 111,
    "Opp": 104,
    "W": 5,
    "L": 0,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 6,
    "Date": "Fri Nov 11 2005",
    "": 0,
    "Opponent": "Portland Trail Blazers",
    "Tm": 84,
    "Opp": 81,
    "W": 6,
    "L": 0,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 7,
    "Date": "Tue Nov 15 2005",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 115,
    "Opp": 100,
    "W": 7,
    "L": 0,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 8,
    "Date": "Fri Nov 18 2005",
    "": 0,
    "Opponent": "Houston Rockets",
    "Tm": 78,
    "Opp": 70,
    "W": 8,
    "L": 0,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 9,
    "Date": "Sat Nov 19 2005",
    "": 0,
    "Opponent": "Dallas Mavericks",
    "Tm": 82,
    "Opp": 119,
    "W": 8,
    "L": 1,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 10,
    "Date": "Wed Nov 23 2005",
    "": 0,
    "Opponent": "Denver Nuggets",
    "Tm": 114,
    "Opp": 89,
    "W": 9,
    "L": 1,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 11,
    "Date": "Fri Nov 25 2005",
    "": "2OT",
    "Opponent": "Washington Wizards",
    "Tm": 114,
    "Opp": 120,
    "W": 9,
    "L": 2,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 12,
    "Date": "Sat Nov 26 2005",
    "": 0,
    "Opponent": "Milwaukee Bucks",
    "Tm": 85,
    "Opp": 76,
    "W": 10,
    "L": 2,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 13,
    "Date": "Wed Nov 30 2005",
    "": 0,
    "Opponent": "New Jersey Nets",
    "Tm": 93,
    "Opp": 83,
    "W": 11,
    "L": 2,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 14,
    "Date": "Fri Dec 2 2005",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 106,
    "Opp": 98,
    "W": 12,
    "L": 2,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 15,
    "Date": "Sat Dec 3 2005",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 92,
    "Opp": 79,
    "W": 13,
    "L": 2,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 16,
    "Date": "Fri Dec 9 2005",
    "": 0,
    "Opponent": "Golden State Warriors",
    "Tm": 106,
    "Opp": 103,
    "W": 14,
    "L": 2,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 17,
    "Date": "Sun Dec 11 2005",
    "": 0,
    "Opponent": "Los Angeles Clippers",
    "Tm": 109,
    "Opp": 101,
    "W": 15,
    "L": 2,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 18,
    "Date": "Mon Dec 12 2005",
    "": 0,
    "Opponent": "Utah Jazz",
    "Tm": 78,
    "Opp": 92,
    "W": 15,
    "L": 3,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 19,
    "Date": "Wed Dec 14 2005",
    "": 0,
    "Opponent": "Sacramento Kings",
    "Tm": 109,
    "Opp": 98,
    "W": 16,
    "L": 3,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 20,
    "Date": "Fri Dec 16 2005",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 110,
    "Opp": 82,
    "W": 17,
    "L": 3,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 21,
    "Date": "Sat Dec 17 2005",
    "": 0,
    "Opponent": "Charlotte Bobcats",
    "Tm": 103,
    "Opp": 78,
    "W": 18,
    "L": 3,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 22,
    "Date": "Mon Dec 19 2005",
    "": "2OT",
    "Opponent": "Memphis Grizzlies",
    "Tm": 106,
    "Opp": 104,
    "W": 19,
    "L": 3,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 23,
    "Date": "Tue Dec 20 2005",
    "": 0,
    "Opponent": "Portland Trail Blazers",
    "Tm": 93,
    "Opp": 89,
    "W": 20,
    "L": 3,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 24,
    "Date": "Fri Dec 23 2005",
    "": 0,
    "Opponent": "Golden State Warriors",
    "Tm": 97,
    "Opp": 85,
    "W": 21,
    "L": 3,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 25,
    "Date": "Sun Dec 25 2005",
    "": 0,
    "Opponent": "San Antonio Spurs",
    "Tm": 85,
    "Opp": 70,
    "W": 22,
    "L": 3,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 26,
    "Date": "Tue Dec 27 2005",
    "": 0,
    "Opponent": "Toronto Raptors",
    "Tm": 113,
    "Opp": 106,
    "W": 23,
    "L": 3,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 27,
    "Date": "Thu Dec 29 2005",
    "": 0,
    "Opponent": "Miami Heat",
    "Tm": 106,
    "Opp": 101,
    "W": 24,
    "L": 3,
    "Streak": "W 9",
    "Notes": 0
  },
  {
    "G": 28,
    "Date": "Sat Dec 31 2005",
    "": 0,
    "Opponent": "Cleveland Cavaliers",
    "Tm": 84,
    "Opp": 97,
    "W": 24,
    "L": 4,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 29,
    "Date": "Tue Jan 3 2006",
    "": 0,
    "Opponent": "Orlando Magic",
    "Tm": 108,
    "Opp": 99,
    "W": 25,
    "L": 4,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 30,
    "Date": "Fri Jan 6 2006",
    "": 0,
    "Opponent": "Seattle SuperSonics",
    "Tm": 97,
    "Opp": 85,
    "W": 26,
    "L": 4,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 31,
    "Date": "Sat Jan 7 2006",
    "": "OT",
    "Opponent": "Utah Jazz",
    "Tm": 90,
    "Opp": 94,
    "W": 26,
    "L": 5,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 32,
    "Date": "Tue Jan 10 2006",
    "": 0,
    "Opponent": "New Orleans/Oklahoma City Hornets",
    "Tm": 96,
    "Opp": 86,
    "W": 27,
    "L": 5,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 33,
    "Date": "Thu Jan 12 2006",
    "": 0,
    "Opponent": "San Antonio Spurs",
    "Tm": 83,
    "Opp": 68,
    "W": 28,
    "L": 5,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 34,
    "Date": "Sat Jan 14 2006",
    "": 0,
    "Opponent": "Charlotte Bobcats",
    "Tm": 114,
    "Opp": 91,
    "W": 29,
    "L": 5,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 35,
    "Date": "Mon Jan 16 2006",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 94,
    "Opp": 84,
    "W": 30,
    "L": 5,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 36,
    "Date": "Wed Jan 18 2006",
    "": 0,
    "Opponent": "Atlanta Hawks",
    "Tm": 117,
    "Opp": 89,
    "W": 31,
    "L": 5,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 37,
    "Date": "Thu Jan 19 2006",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 105,
    "Opp": 79,
    "W": 32,
    "L": 5,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 38,
    "Date": "Sun Jan 22 2006",
    "": 0,
    "Opponent": "Houston Rockets",
    "Tm": 99,
    "Opp": 97,
    "W": 33,
    "L": 5,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 39,
    "Date": "Tue Jan 24 2006",
    "": 0,
    "Opponent": "Minnesota Timberwolves",
    "Tm": 107,
    "Opp": 83,
    "W": 34,
    "L": 5,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 40,
    "Date": "Wed Jan 25 2006",
    "": "OT",
    "Opponent": "Milwaukee Bucks",
    "Tm": 106,
    "Opp": 102,
    "W": 35,
    "L": 5,
    "Streak": "W 9",
    "Notes": 0
  },
  {
    "G": 41,
    "Date": "Fri Jan 27 2006",
    "": 0,
    "Opponent": "Memphis Grizzlies",
    "Tm": 95,
    "Opp": 89,
    "W": 36,
    "L": 5,
    "Streak": "W 10",
    "Notes": 0
  },
  {
    "G": 42,
    "Date": "Sun Jan 29 2006",
    "": 0,
    "Opponent": "Los Angeles Lakers",
    "Tm": 102,
    "Opp": 93,
    "W": 37,
    "L": 5,
    "Streak": "W 11",
    "Notes": 0
  },
  {
    "G": 43,
    "Date": "Tue Jan 31 2006",
    "": 0,
    "Opponent": "New Jersey Nets",
    "Tm": 84,
    "Opp": 91,
    "W": 37,
    "L": 6,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 44,
    "Date": "Wed Feb 1 2006",
    "": 0,
    "Opponent": "Minnesota Timberwolves",
    "Tm": 90,
    "Opp": 74,
    "W": 38,
    "L": 6,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 45,
    "Date": "Fri Feb 3 2006",
    "": 0,
    "Opponent": "Philadelphia 76ers",
    "Tm": 87,
    "Opp": 80,
    "W": 39,
    "L": 6,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 46,
    "Date": "Sat Feb 4 2006",
    "": 0,
    "Opponent": "Indiana Pacers",
    "Tm": 85,
    "Opp": 93,
    "W": 39,
    "L": 7,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 47,
    "Date": "Tue Feb 7 2006",
    "": 0,
    "Opponent": "Atlanta Hawks",
    "Tm": 98,
    "Opp": 99,
    "W": 39,
    "L": 8,
    "Streak": "L 2",
    "Notes": 0
  },
  {
    "G": 48,
    "Date": "Wed Feb 8 2006",
    "": 0,
    "Opponent": "Los Angeles Clippers",
    "Tm": 97,
    "Opp": 87,
    "W": 40,
    "L": 8,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 49,
    "Date": "Fri Feb 10 2006",
    "": 0,
    "Opponent": "Orlando Magic",
    "Tm": 84,
    "Opp": 73,
    "W": 41,
    "L": 8,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 50,
    "Date": "Sun Feb 12 2006",
    "": 0,
    "Opponent": "Miami Heat",
    "Tm": 98,
    "Opp": 100,
    "W": 41,
    "L": 9,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 51,
    "Date": "Tue Feb 14 2006",
    "": 0,
    "Opponent": "New Jersey Nets",
    "Tm": 85,
    "Opp": 71,
    "W": 42,
    "L": 9,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 52,
    "Date": "Tue Feb 21 2006",
    "": 0,
    "Opponent": "Atlanta Hawks",
    "Tm": 97,
    "Opp": 87,
    "W": 43,
    "L": 9,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 53,
    "Date": "Thu Feb 23 2006",
    "": 0,
    "Opponent": "Indiana Pacers",
    "Tm": 88,
    "Opp": 83,
    "W": 44,
    "L": 9,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 54,
    "Date": "Fri Feb 24 2006",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 95,
    "Opp": 87,
    "W": 45,
    "L": 9,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 55,
    "Date": "Sun Feb 26 2006",
    "": 0,
    "Opponent": "Cleveland Cavaliers",
    "Tm": 90,
    "Opp": 78,
    "W": 46,
    "L": 9,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 56,
    "Date": "Mon Feb 27 2006",
    "": 0,
    "Opponent": "Cleveland Cavaliers",
    "Tm": 84,
    "Opp": 72,
    "W": 47,
    "L": 9,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 57,
    "Date": "Wed Mar 1 2006",
    "": 0,
    "Opponent": "Denver Nuggets",
    "Tm": 87,
    "Opp": 98,
    "W": 47,
    "L": 10,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 58,
    "Date": "Fri Mar 3 2006",
    "": 0,
    "Opponent": "Seattle SuperSonics",
    "Tm": 98,
    "Opp": 96,
    "W": 48,
    "L": 10,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 59,
    "Date": "Sat Mar 4 2006",
    "": 0,
    "Opponent": "Los Angeles Lakers",
    "Tm": 94,
    "Opp": 105,
    "W": 48,
    "L": 11,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 60,
    "Date": "Wed Mar 8 2006",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 106,
    "Opp": 101,
    "W": 49,
    "L": 11,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 61,
    "Date": "Sat Mar 11 2006",
    "": 0,
    "Opponent": "Washington Wizards",
    "Tm": 92,
    "Opp": 110,
    "W": 49,
    "L": 12,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 62,
    "Date": "Sun Mar 12 2006",
    "": 0,
    "Opponent": "Charlotte Bobcats",
    "Tm": 94,
    "Opp": 78,
    "W": 50,
    "L": 12,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 63,
    "Date": "Wed Mar 15 2006",
    "": 0,
    "Opponent": "Toronto Raptors",
    "Tm": 105,
    "Opp": 98,
    "W": 51,
    "L": 12,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 64,
    "Date": "Fri Mar 17 2006",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 103,
    "Opp": 105,
    "W": 51,
    "L": 13,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 65,
    "Date": "Sat Mar 18 2006",
    "": 0,
    "Opponent": "Charlotte Bobcats",
    "Tm": 108,
    "Opp": 103,
    "W": 52,
    "L": 13,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 66,
    "Date": "Mon Mar 20 2006",
    "": 0,
    "Opponent": "Atlanta Hawks",
    "Tm": 91,
    "Opp": 84,
    "W": 53,
    "L": 13,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 67,
    "Date": "Wed Mar 22 2006",
    "": 0,
    "Opponent": "Miami Heat",
    "Tm": 82,
    "Opp": 73,
    "W": 54,
    "L": 13,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 68,
    "Date": "Fri Mar 24 2006",
    "": 0,
    "Opponent": "Indiana Pacers",
    "Tm": 75,
    "Opp": 72,
    "W": 55,
    "L": 13,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 69,
    "Date": "Sun Mar 26 2006",
    "": 0,
    "Opponent": "New Jersey Nets",
    "Tm": 74,
    "Opp": 79,
    "W": 55,
    "L": 14,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 70,
    "Date": "Tue Mar 28 2006",
    "": 0,
    "Opponent": "Dallas Mavericks",
    "Tm": 97,
    "Opp": 90,
    "W": 56,
    "L": 14,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 71,
    "Date": "Wed Mar 29 2006",
    "": 0,
    "Opponent": "Philadelphia 76ers",
    "Tm": 101,
    "Opp": 91,
    "W": 57,
    "L": 14,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 72,
    "Date": "Fri Mar 31 2006",
    "": 0,
    "Opponent": "Milwaukee Bucks",
    "Tm": 112,
    "Opp": 105,
    "W": 58,
    "L": 14,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 73,
    "Date": "Sun Apr 2 2006",
    "": 0,
    "Opponent": "Phoenix Suns",
    "Tm": 109,
    "Opp": 102,
    "W": 59,
    "L": 14,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 74,
    "Date": "Tue Apr 4 2006",
    "": 0,
    "Opponent": "New Orleans/Oklahoma City Hornets",
    "Tm": 101,
    "Opp": 93,
    "W": 60,
    "L": 14,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 75,
    "Date": "Thu Apr 6 2006",
    "": 0,
    "Opponent": "Miami Heat",
    "Tm": 95,
    "Opp": 82,
    "W": 61,
    "L": 14,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 76,
    "Date": "Fri Apr 7 2006",
    "": 0,
    "Opponent": "Orlando Magic",
    "Tm": 87,
    "Opp": 89,
    "W": 61,
    "L": 15,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 77,
    "Date": "Sun Apr 9 2006",
    "": 0,
    "Opponent": "Indiana Pacers",
    "Tm": 98,
    "Opp": 73,
    "W": 62,
    "L": 15,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 78,
    "Date": "Wed Apr 12 2006",
    "": 0,
    "Opponent": "Cleveland Cavaliers",
    "Tm": 96,
    "Opp": 73,
    "W": 63,
    "L": 15,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 79,
    "Date": "Fri Apr 14 2006",
    "": 0,
    "Opponent": "Toronto Raptors",
    "Tm": 103,
    "Opp": 108,
    "W": 63,
    "L": 16,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 80,
    "Date": "Sun Apr 16 2006",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 103,
    "Opp": 97,
    "W": 64,
    "L": 16,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 81,
    "Date": "Mon Apr 17 2006",
    "": 0,
    "Opponent": "Milwaukee Bucks",
    "Tm": 93,
    "Opp": 113,
    "W": 64,
    "L": 17,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 82,
    "Date": "Wed Apr 19 2006",
    "": 0,
    "Opponent": "Washington Wizards",
    "Tm": 80,
    "Opp": 96,
    "W": 64,
    "L": 18,
    "Streak": "L 2",
    "Notes": 0
  }
]