var _2008_celtics = [
  {
    "G": 1,
    "Date": "Fri Nov 2 2007",
    "": 0,
    "Opponent": "Washington Wizards",
    "Tm": 103,
    "Opp": 83,
    "W": 1,
    "L": 0,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 2,
    "Date": "Sun Nov 4 2007",
    "": "OT",
    "Opponent": "Toronto Raptors",
    "Tm": 98,
    "Opp": 95,
    "W": 2,
    "L": 0,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 3,
    "Date": "Wed Nov 7 2007",
    "": 0,
    "Opponent": "Denver Nuggets",
    "Tm": 119,
    "Opp": 93,
    "W": 3,
    "L": 0,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 4,
    "Date": "Fri Nov 9 2007",
    "": 0,
    "Opponent": "Atlanta Hawks",
    "Tm": 106,
    "Opp": 83,
    "W": 4,
    "L": 0,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 5,
    "Date": "Sat Nov 10 2007",
    "": 0,
    "Opponent": "New Jersey Nets",
    "Tm": 112,
    "Opp": 101,
    "W": 5,
    "L": 0,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 6,
    "Date": "Tue Nov 13 2007",
    "": 0,
    "Opponent": "Indiana Pacers",
    "Tm": 101,
    "Opp": 86,
    "W": 6,
    "L": 0,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 7,
    "Date": "Wed Nov 14 2007",
    "": 0,
    "Opponent": "New Jersey Nets",
    "Tm": 91,
    "Opp": 69,
    "W": 7,
    "L": 0,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 8,
    "Date": "Fri Nov 16 2007",
    "": 0,
    "Opponent": "Miami Heat",
    "Tm": 92,
    "Opp": 91,
    "W": 8,
    "L": 0,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 9,
    "Date": "Sun Nov 18 2007",
    "": 0,
    "Opponent": "Orlando Magic",
    "Tm": 102,
    "Opp": 104,
    "W": 8,
    "L": 1,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 10,
    "Date": "Wed Nov 21 2007",
    "": 0,
    "Opponent": "Golden State Warriors",
    "Tm": 105,
    "Opp": 82,
    "W": 9,
    "L": 1,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 11,
    "Date": "Fri Nov 23 2007",
    "": 0,
    "Opponent": "Los Angeles Lakers",
    "Tm": 107,
    "Opp": 94,
    "W": 10,
    "L": 1,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 12,
    "Date": "Sat Nov 24 2007",
    "": 0,
    "Opponent": "Charlotte Bobcats",
    "Tm": 96,
    "Opp": 95,
    "W": 11,
    "L": 1,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 13,
    "Date": "Tue Nov 27 2007",
    "": "OT",
    "Opponent": "Cleveland Cavaliers",
    "Tm": 104,
    "Opp": 109,
    "W": 11,
    "L": 2,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 14,
    "Date": "Thu Nov 29 2007",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 104,
    "Opp": 59,
    "W": 12,
    "L": 2,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 15,
    "Date": "Fri Nov 30 2007",
    "": 0,
    "Opponent": "Miami Heat",
    "Tm": 95,
    "Opp": 85,
    "W": 13,
    "L": 2,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 16,
    "Date": "Sun Dec 2 2007",
    "": 0,
    "Opponent": "Cleveland Cavaliers",
    "Tm": 80,
    "Opp": 70,
    "W": 14,
    "L": 2,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 17,
    "Date": "Wed Dec 5 2007",
    "": 0,
    "Opponent": "Philadelphia 76ers",
    "Tm": 113,
    "Opp": 103,
    "W": 15,
    "L": 2,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 18,
    "Date": "Fri Dec 7 2007",
    "": 0,
    "Opponent": "Toronto Raptors",
    "Tm": 112,
    "Opp": 84,
    "W": 16,
    "L": 2,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 19,
    "Date": "Sat Dec 8 2007",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 92,
    "Opp": 81,
    "W": 17,
    "L": 2,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 20,
    "Date": "Wed Dec 12 2007",
    "": 0,
    "Opponent": "Sacramento Kings",
    "Tm": 90,
    "Opp": 78,
    "W": 18,
    "L": 2,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 21,
    "Date": "Fri Dec 14 2007",
    "": 0,
    "Opponent": "Milwaukee Bucks",
    "Tm": 104,
    "Opp": 82,
    "W": 19,
    "L": 2,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 22,
    "Date": "Sun Dec 16 2007",
    "": 0,
    "Opponent": "Toronto Raptors",
    "Tm": 90,
    "Opp": 77,
    "W": 20,
    "L": 2,
    "Streak": "W 9",
    "Notes": 0
  },
  {
    "G": 23,
    "Date": "Wed Dec 19 2007",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 85,
    "Opp": 87,
    "W": 20,
    "L": 3,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 24,
    "Date": "Fri Dec 21 2007",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 107,
    "Opp": 82,
    "W": 21,
    "L": 3,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 25,
    "Date": "Sun Dec 23 2007",
    "": 0,
    "Opponent": "Orlando Magic",
    "Tm": 103,
    "Opp": 91,
    "W": 22,
    "L": 3,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 26,
    "Date": "Wed Dec 26 2007",
    "": 0,
    "Opponent": "Sacramento Kings",
    "Tm": 89,
    "Opp": 69,
    "W": 23,
    "L": 3,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 27,
    "Date": "Thu Dec 27 2007",
    "": 0,
    "Opponent": "Seattle SuperSonics",
    "Tm": 104,
    "Opp": 96,
    "W": 24,
    "L": 3,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 28,
    "Date": "Sat Dec 29 2007",
    "": 0,
    "Opponent": "Utah Jazz",
    "Tm": 104,
    "Opp": 98,
    "W": 25,
    "L": 3,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 29,
    "Date": "Sun Dec 30 2007",
    "": 0,
    "Opponent": "Los Angeles Lakers",
    "Tm": 110,
    "Opp": 91,
    "W": 26,
    "L": 3,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 30,
    "Date": "Wed Jan 2 2008",
    "": 0,
    "Opponent": "Houston Rockets",
    "Tm": 97,
    "Opp": 93,
    "W": 27,
    "L": 3,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 31,
    "Date": "Fri Jan 4 2008",
    "": 0,
    "Opponent": "Memphis Grizzlies",
    "Tm": 100,
    "Opp": 96,
    "W": 28,
    "L": 3,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 32,
    "Date": "Sat Jan 5 2008",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 92,
    "Opp": 85,
    "W": 29,
    "L": 3,
    "Streak": "W 9",
    "Notes": 0
  },
  {
    "G": 33,
    "Date": "Wed Jan 9 2008",
    "": 0,
    "Opponent": "Charlotte Bobcats",
    "Tm": 83,
    "Opp": 95,
    "W": 29,
    "L": 4,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 34,
    "Date": "Fri Jan 11 2008",
    "": 0,
    "Opponent": "New Jersey Nets",
    "Tm": 86,
    "Opp": 77,
    "W": 30,
    "L": 4,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 35,
    "Date": "Sat Jan 12 2008",
    "": 0,
    "Opponent": "Washington Wizards",
    "Tm": 78,
    "Opp": 85,
    "W": 30,
    "L": 5,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 36,
    "Date": "Mon Jan 14 2008",
    "": 0,
    "Opponent": "Washington Wizards",
    "Tm": 83,
    "Opp": 88,
    "W": 30,
    "L": 6,
    "Streak": "L 2",
    "Notes": 0
  },
  {
    "G": 37,
    "Date": "Wed Jan 16 2008",
    "": 0,
    "Opponent": "Portland Trail Blazers",
    "Tm": 100,
    "Opp": 90,
    "W": 31,
    "L": 6,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 38,
    "Date": "Fri Jan 18 2008",
    "": 0,
    "Opponent": "Philadelphia 76ers",
    "Tm": 116,
    "Opp": 89,
    "W": 32,
    "L": 6,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 39,
    "Date": "Mon Jan 21 2008",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 109,
    "Opp": 93,
    "W": 33,
    "L": 6,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 40,
    "Date": "Wed Jan 23 2008",
    "": 0,
    "Opponent": "Toronto Raptors",
    "Tm": 112,
    "Opp": 114,
    "W": 33,
    "L": 7,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 41,
    "Date": "Fri Jan 25 2008",
    "": 0,
    "Opponent": "Minnesota Timberwolves",
    "Tm": 87,
    "Opp": 86,
    "W": 34,
    "L": 7,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 42,
    "Date": "Sun Jan 27 2008",
    "": 0,
    "Opponent": "Orlando Magic",
    "Tm": 93,
    "Opp": 96,
    "W": 34,
    "L": 8,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 43,
    "Date": "Tue Jan 29 2008",
    "": 0,
    "Opponent": "Miami Heat",
    "Tm": 117,
    "Opp": 87,
    "W": 35,
    "L": 8,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 44,
    "Date": "Thu Jan 31 2008",
    "": 0,
    "Opponent": "Dallas Mavericks",
    "Tm": 96,
    "Opp": 90,
    "W": 36,
    "L": 8,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 45,
    "Date": "Tue Feb 5 2008",
    "": 0,
    "Opponent": "Cleveland Cavaliers",
    "Tm": 113,
    "Opp": 114,
    "W": 36,
    "L": 9,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 46,
    "Date": "Wed Feb 6 2008",
    "": 0,
    "Opponent": "Los Angeles Clippers",
    "Tm": 111,
    "Opp": 100,
    "W": 37,
    "L": 9,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 47,
    "Date": "Fri Feb 8 2008",
    "": 0,
    "Opponent": "Minnesota Timberwolves",
    "Tm": 88,
    "Opp": 86,
    "W": 38,
    "L": 9,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 48,
    "Date": "Sun Feb 10 2008",
    "": 0,
    "Opponent": "San Antonio Spurs",
    "Tm": 98,
    "Opp": 90,
    "W": 39,
    "L": 9,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 49,
    "Date": "Tue Feb 12 2008",
    "": 0,
    "Opponent": "Indiana Pacers",
    "Tm": 104,
    "Opp": 97,
    "W": 40,
    "L": 9,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 50,
    "Date": "Wed Feb 13 2008",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 111,
    "Opp": 103,
    "W": 41,
    "L": 9,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 51,
    "Date": "Tue Feb 19 2008",
    "": 0,
    "Opponent": "Denver Nuggets",
    "Tm": 118,
    "Opp": 124,
    "W": 41,
    "L": 10,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 52,
    "Date": "Wed Feb 20 2008",
    "": 0,
    "Opponent": "Golden State Warriors",
    "Tm": 117,
    "Opp": 119,
    "W": 41,
    "L": 11,
    "Streak": "L 2",
    "Notes": 0
  },
  {
    "G": 53,
    "Date": "Fri Feb 22 2008",
    "": 0,
    "Opponent": "Phoenix Suns",
    "Tm": 77,
    "Opp": 85,
    "W": 41,
    "L": 12,
    "Streak": "L 3",
    "Notes": 0
  },
  {
    "G": 54,
    "Date": "Sun Feb 24 2008",
    "": 0,
    "Opponent": "Portland Trail Blazers",
    "Tm": 112,
    "Opp": 102,
    "W": 42,
    "L": 12,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 55,
    "Date": "Mon Feb 25 2008",
    "": 0,
    "Opponent": "Los Angeles Clippers",
    "Tm": 104,
    "Opp": 76,
    "W": 43,
    "L": 12,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 56,
    "Date": "Wed Feb 27 2008",
    "": 0,
    "Opponent": "Cleveland Cavaliers",
    "Tm": 92,
    "Opp": 87,
    "W": 44,
    "L": 12,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 57,
    "Date": "Fri Feb 29 2008",
    "": 0,
    "Opponent": "Charlotte Bobcats",
    "Tm": 108,
    "Opp": 100,
    "W": 45,
    "L": 12,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 58,
    "Date": "Sun Mar 2 2008",
    "": 0,
    "Opponent": "Atlanta Hawks",
    "Tm": 98,
    "Opp": 88,
    "W": 46,
    "L": 12,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 59,
    "Date": "Wed Mar 5 2008",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 90,
    "Opp": 78,
    "W": 47,
    "L": 12,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 60,
    "Date": "Fri Mar 7 2008",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 116,
    "Opp": 93,
    "W": 48,
    "L": 12,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 61,
    "Date": "Sat Mar 8 2008",
    "": 0,
    "Opponent": "Memphis Grizzlies",
    "Tm": 119,
    "Opp": 89,
    "W": 49,
    "L": 12,
    "Streak": "W 8",
    "Notes": 0
  },
  {
    "G": 62,
    "Date": "Mon Mar 10 2008",
    "": 0,
    "Opponent": "Philadelphia 76ers",
    "Tm": 100,
    "Opp": 86,
    "W": 50,
    "L": 12,
    "Streak": "W 9",
    "Notes": 0
  },
  {
    "G": 63,
    "Date": "Wed Mar 12 2008",
    "": 0,
    "Opponent": "Seattle SuperSonics",
    "Tm": 111,
    "Opp": 82,
    "W": 51,
    "L": 12,
    "Streak": "W 10",
    "Notes": 0
  },
  {
    "G": 64,
    "Date": "Fri Mar 14 2008",
    "": 0,
    "Opponent": "Utah Jazz",
    "Tm": 92,
    "Opp": 110,
    "W": 51,
    "L": 13,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 65,
    "Date": "Sat Mar 15 2008",
    "": 0,
    "Opponent": "Milwaukee Bucks",
    "Tm": 99,
    "Opp": 77,
    "W": 52,
    "L": 13,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 66,
    "Date": "Mon Mar 17 2008",
    "": 0,
    "Opponent": "San Antonio Spurs",
    "Tm": 93,
    "Opp": 91,
    "W": 53,
    "L": 13,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 67,
    "Date": "Tue Mar 18 2008",
    "": 0,
    "Opponent": "Houston Rockets",
    "Tm": 94,
    "Opp": 74,
    "W": 54,
    "L": 13,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 68,
    "Date": "Thu Mar 20 2008",
    "": 0,
    "Opponent": "Dallas Mavericks",
    "Tm": 94,
    "Opp": 90,
    "W": 55,
    "L": 13,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 69,
    "Date": "Sat Mar 22 2008",
    "": 0,
    "Opponent": "New Orleans Hornets",
    "Tm": 106,
    "Opp": 113,
    "W": 55,
    "L": 14,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 70,
    "Date": "Mon Mar 24 2008",
    "": 0,
    "Opponent": "Philadelphia 76ers",
    "Tm": 90,
    "Opp": 95,
    "W": 55,
    "L": 15,
    "Streak": "L 2",
    "Notes": 0
  },
  {
    "G": 71,
    "Date": "Wed Mar 26 2008",
    "": 0,
    "Opponent": "Phoenix Suns",
    "Tm": 117,
    "Opp": 97,
    "W": 56,
    "L": 15,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 72,
    "Date": "Fri Mar 28 2008",
    "": 0,
    "Opponent": "New Orleans Hornets",
    "Tm": 112,
    "Opp": 92,
    "W": 57,
    "L": 15,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 73,
    "Date": "Sun Mar 30 2008",
    "": 0,
    "Opponent": "Miami Heat",
    "Tm": 88,
    "Opp": 62,
    "W": 58,
    "L": 15,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 74,
    "Date": "Tue Apr 1 2008",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 106,
    "Opp": 92,
    "W": 59,
    "L": 15,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 75,
    "Date": "Wed Apr 2 2008",
    "": 0,
    "Opponent": "Indiana Pacers",
    "Tm": 92,
    "Opp": 77,
    "W": 60,
    "L": 15,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 76,
    "Date": "Sat Apr 5 2008",
    "": 0,
    "Opponent": "Charlotte Bobcats",
    "Tm": 101,
    "Opp": 78,
    "W": 61,
    "L": 15,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 77,
    "Date": "Tue Apr 8 2008",
    "": "OT",
    "Opponent": "Milwaukee Bucks",
    "Tm": 107,
    "Opp": 104,
    "W": 62,
    "L": 15,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 78,
    "Date": "Wed Apr 9 2008",
    "": 0,
    "Opponent": "Washington Wizards",
    "Tm": 95,
    "Opp": 109,
    "W": 62,
    "L": 16,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 79,
    "Date": "Fri Apr 11 2008",
    "": 0,
    "Opponent": "Milwaukee Bucks",
    "Tm": 102,
    "Opp": 86,
    "W": 63,
    "L": 16,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 80,
    "Date": "Sat Apr 12 2008",
    "": 0,
    "Opponent": "Atlanta Hawks",
    "Tm": 99,
    "Opp": 89,
    "W": 64,
    "L": 16,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 81,
    "Date": "Mon Apr 14 2008",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 99,
    "Opp": 93,
    "W": 65,
    "L": 16,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 82,
    "Date": "Wed Apr 16 2008",
    "": 0,
    "Opponent": "New Jersey Nets",
    "Tm": 105,
    "Opp": 94,
    "W": 66,
    "L": 16,
    "Streak": "W 4",
    "Notes": 0
  }
]