var _2009_lakers = [
  {
    "G": 1,
    "Date": "Tue Oct 28 2008",
    "": 0,
    "Opponent": "Portland Trail Blazers",
    "Tm": 96,
    "Opp": 76,
    "W": 1,
    "L": 0,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 2,
    "Date": "Wed Oct 29 2008",
    "": 0,
    "Opponent": "Los Angeles Clippers",
    "Tm": 117,
    "Opp": 79,
    "W": 2,
    "L": 0,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 3,
    "Date": "Sat Nov 1 2008",
    "": 0,
    "Opponent": "Denver Nuggets",
    "Tm": 104,
    "Opp": 97,
    "W": 3,
    "L": 0,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 4,
    "Date": "Wed Nov 5 2008",
    "": 0,
    "Opponent": "Los Angeles Clippers",
    "Tm": 106,
    "Opp": 88,
    "W": 4,
    "L": 0,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 5,
    "Date": "Sun Nov 9 2008",
    "": 0,
    "Opponent": "Houston Rockets",
    "Tm": 111,
    "Opp": 82,
    "W": 5,
    "L": 0,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 6,
    "Date": "Tue Nov 11 2008",
    "": 0,
    "Opponent": "Dallas Mavericks",
    "Tm": 106,
    "Opp": 99,
    "W": 6,
    "L": 0,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 7,
    "Date": "Wed Nov 12 2008",
    "": 0,
    "Opponent": "New Orleans Hornets",
    "Tm": 93,
    "Opp": 86,
    "W": 7,
    "L": 0,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 8,
    "Date": "Fri Nov 14 2008",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 95,
    "Opp": 106,
    "W": 7,
    "L": 1,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 9,
    "Date": "Tue Nov 18 2008",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 116,
    "Opp": 109,
    "W": 8,
    "L": 1,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 10,
    "Date": "Thu Nov 20 2008",
    "": 0,
    "Opponent": "Phoenix Suns",
    "Tm": 105,
    "Opp": 92,
    "W": 9,
    "L": 1,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 11,
    "Date": "Fri Nov 21 2008",
    "": 0,
    "Opponent": "Denver Nuggets",
    "Tm": 104,
    "Opp": 90,
    "W": 10,
    "L": 1,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 12,
    "Date": "Sun Nov 23 2008",
    "": 0,
    "Opponent": "Sacramento Kings",
    "Tm": 118,
    "Opp": 108,
    "W": 11,
    "L": 1,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 13,
    "Date": "Tue Nov 25 2008",
    "": 0,
    "Opponent": "New Jersey Nets",
    "Tm": 120,
    "Opp": 93,
    "W": 12,
    "L": 1,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 14,
    "Date": "Fri Nov 28 2008",
    "": 0,
    "Opponent": "Dallas Mavericks",
    "Tm": 114,
    "Opp": 107,
    "W": 13,
    "L": 1,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 15,
    "Date": "Sun Nov 30 2008",
    "": 0,
    "Opponent": "Toronto Raptors",
    "Tm": 112,
    "Opp": 99,
    "W": 14,
    "L": 1,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 16,
    "Date": "Tue Dec 2 2008",
    "": 0,
    "Opponent": "Indiana Pacers",
    "Tm": 117,
    "Opp": 118,
    "W": 14,
    "L": 2,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 17,
    "Date": "Wed Dec 3 2008",
    "": 0,
    "Opponent": "Philadelphia 76ers",
    "Tm": 114,
    "Opp": 102,
    "W": 15,
    "L": 2,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 18,
    "Date": "Fri Dec 5 2008",
    "": 0,
    "Opponent": "Washington Wizards",
    "Tm": 106,
    "Opp": 104,
    "W": 16,
    "L": 2,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 19,
    "Date": "Sun Dec 7 2008",
    "": 0,
    "Opponent": "Milwaukee Bucks",
    "Tm": 105,
    "Opp": 92,
    "W": 17,
    "L": 2,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 20,
    "Date": "Tue Dec 9 2008",
    "": 0,
    "Opponent": "Sacramento Kings",
    "Tm": 101,
    "Opp": 113,
    "W": 17,
    "L": 3,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 21,
    "Date": "Wed Dec 10 2008",
    "": 0,
    "Opponent": "Phoenix Suns",
    "Tm": 115,
    "Opp": 110,
    "W": 18,
    "L": 3,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 22,
    "Date": "Fri Dec 12 2008",
    "": 0,
    "Opponent": "Sacramento Kings",
    "Tm": 112,
    "Opp": 103,
    "W": 19,
    "L": 3,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 23,
    "Date": "Sun Dec 14 2008",
    "": 0,
    "Opponent": "Minnesota Timberwolves",
    "Tm": 98,
    "Opp": 86,
    "W": 20,
    "L": 3,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 24,
    "Date": "Tue Dec 16 2008",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 116,
    "Opp": 114,
    "W": 21,
    "L": 3,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 25,
    "Date": "Fri Dec 19 2008",
    "": 0,
    "Opponent": "Miami Heat",
    "Tm": 87,
    "Opp": 89,
    "W": 21,
    "L": 4,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 26,
    "Date": "Sat Dec 20 2008",
    "": 0,
    "Opponent": "Orlando Magic",
    "Tm": 103,
    "Opp": 106,
    "W": 21,
    "L": 5,
    "Streak": "L 2",
    "Notes": 0
  },
  {
    "G": 27,
    "Date": "Mon Dec 22 2008",
    "": 0,
    "Opponent": "Memphis Grizzlies",
    "Tm": 105,
    "Opp": 96,
    "W": 22,
    "L": 5,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 28,
    "Date": "Tue Dec 23 2008",
    "": 0,
    "Opponent": "New Orleans Hornets",
    "Tm": 100,
    "Opp": 87,
    "W": 23,
    "L": 5,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 29,
    "Date": "Thu Dec 25 2008",
    "": 0,
    "Opponent": "Boston Celtics",
    "Tm": 92,
    "Opp": 83,
    "W": 24,
    "L": 5,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 30,
    "Date": "Sun Dec 28 2008",
    "": 0,
    "Opponent": "Golden State Warriors",
    "Tm": 130,
    "Opp": 113,
    "W": 25,
    "L": 5,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 31,
    "Date": "Fri Jan 2 2009",
    "": 0,
    "Opponent": "Utah Jazz",
    "Tm": 113,
    "Opp": 100,
    "W": 26,
    "L": 5,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 32,
    "Date": "Sun Jan 4 2009",
    "": 0,
    "Opponent": "Portland Trail Blazers",
    "Tm": 100,
    "Opp": 86,
    "W": 27,
    "L": 5,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 33,
    "Date": "Tue Jan 6 2009",
    "": 0,
    "Opponent": "New Orleans Hornets",
    "Tm": 105,
    "Opp": 116,
    "W": 27,
    "L": 6,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 34,
    "Date": "Wed Jan 7 2009",
    "": 0,
    "Opponent": "Golden State Warriors",
    "Tm": 114,
    "Opp": 106,
    "W": 28,
    "L": 6,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 35,
    "Date": "Fri Jan 9 2009",
    "": 0,
    "Opponent": "Indiana Pacers",
    "Tm": 121,
    "Opp": 119,
    "W": 29,
    "L": 6,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 36,
    "Date": "Sun Jan 11 2009",
    "": 0,
    "Opponent": "Miami Heat",
    "Tm": 108,
    "Opp": 105,
    "W": 30,
    "L": 6,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 37,
    "Date": "Tue Jan 13 2009",
    "": 0,
    "Opponent": "Houston Rockets",
    "Tm": 105,
    "Opp": 100,
    "W": 31,
    "L": 6,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 38,
    "Date": "Wed Jan 14 2009",
    "": 0,
    "Opponent": "San Antonio Spurs",
    "Tm": 111,
    "Opp": 112,
    "W": 31,
    "L": 7,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 39,
    "Date": "Fri Jan 16 2009",
    "": 0,
    "Opponent": "Orlando Magic",
    "Tm": 103,
    "Opp": 109,
    "W": 31,
    "L": 8,
    "Streak": "L 2",
    "Notes": 0
  },
  {
    "G": 40,
    "Date": "Mon Jan 19 2009",
    "": 0,
    "Opponent": "Cleveland Cavaliers",
    "Tm": 105,
    "Opp": 88,
    "W": 32,
    "L": 8,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 41,
    "Date": "Wed Jan 21 2009",
    "": 0,
    "Opponent": "Los Angeles Clippers",
    "Tm": 108,
    "Opp": 97,
    "W": 33,
    "L": 8,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 42,
    "Date": "Thu Jan 22 2009",
    "": 0,
    "Opponent": "Washington Wizards",
    "Tm": 117,
    "Opp": 97,
    "W": 34,
    "L": 8,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 43,
    "Date": "Sun Jan 25 2009",
    "": 0,
    "Opponent": "San Antonio Spurs",
    "Tm": 99,
    "Opp": 85,
    "W": 35,
    "L": 8,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 44,
    "Date": "Tue Jan 27 2009",
    "": "2OT",
    "Opponent": "Charlotte Bobcats",
    "Tm": 110,
    "Opp": 117,
    "W": 35,
    "L": 9,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 45,
    "Date": "Fri Jan 30 2009",
    "": 0,
    "Opponent": "Minnesota Timberwolves",
    "Tm": 132,
    "Opp": 119,
    "W": 36,
    "L": 9,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 46,
    "Date": "Sat Jan 31 2009",
    "": 0,
    "Opponent": "Memphis Grizzlies",
    "Tm": 115,
    "Opp": 98,
    "W": 37,
    "L": 9,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 47,
    "Date": "Mon Feb 2 2009",
    "": 0,
    "Opponent": "New York Knicks",
    "Tm": 126,
    "Opp": 117,
    "W": 38,
    "L": 9,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 48,
    "Date": "Wed Feb 4 2009",
    "": 0,
    "Opponent": "Toronto Raptors",
    "Tm": 115,
    "Opp": 107,
    "W": 39,
    "L": 9,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 49,
    "Date": "Thu Feb 5 2009",
    "": "OT",
    "Opponent": "Boston Celtics",
    "Tm": 110,
    "Opp": 109,
    "W": 40,
    "L": 9,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 50,
    "Date": "Sun Feb 8 2009",
    "": 0,
    "Opponent": "Cleveland Cavaliers",
    "Tm": 101,
    "Opp": 91,
    "W": 41,
    "L": 9,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 51,
    "Date": "Tue Feb 10 2009",
    "": 0,
    "Opponent": "Oklahoma City Thunder",
    "Tm": 105,
    "Opp": 98,
    "W": 42,
    "L": 9,
    "Streak": "W 7",
    "Notes": 0
  },
  {
    "G": 52,
    "Date": "Wed Feb 11 2009",
    "": 0,
    "Opponent": "Utah Jazz",
    "Tm": 109,
    "Opp": 113,
    "W": 42,
    "L": 10,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 53,
    "Date": "Tue Feb 17 2009",
    "": 0,
    "Opponent": "Atlanta Hawks",
    "Tm": 96,
    "Opp": 83,
    "W": 43,
    "L": 10,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 54,
    "Date": "Wed Feb 18 2009",
    "": 0,
    "Opponent": "Golden State Warriors",
    "Tm": 129,
    "Opp": 121,
    "W": 44,
    "L": 10,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 55,
    "Date": "Fri Feb 20 2009",
    "": "OT",
    "Opponent": "New Orleans Hornets",
    "Tm": 115,
    "Opp": 111,
    "W": 45,
    "L": 10,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 56,
    "Date": "Sun Feb 22 2009",
    "": 0,
    "Opponent": "Minnesota Timberwolves",
    "Tm": 111,
    "Opp": 108,
    "W": 46,
    "L": 10,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 57,
    "Date": "Tue Feb 24 2009",
    "": 0,
    "Opponent": "Oklahoma City Thunder",
    "Tm": 107,
    "Opp": 93,
    "W": 47,
    "L": 10,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 58,
    "Date": "Thu Feb 26 2009",
    "": 0,
    "Opponent": "Phoenix Suns",
    "Tm": 132,
    "Opp": 106,
    "W": 48,
    "L": 10,
    "Streak": "W 6",
    "Notes": 0
  },
  {
    "G": 59,
    "Date": "Fri Feb 27 2009",
    "": 0,
    "Opponent": "Denver Nuggets",
    "Tm": 79,
    "Opp": 90,
    "W": 48,
    "L": 11,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 60,
    "Date": "Sun Mar 1 2009",
    "": 0,
    "Opponent": "Phoenix Suns",
    "Tm": 111,
    "Opp": 118,
    "W": 48,
    "L": 12,
    "Streak": "L 2",
    "Notes": 0
  },
  {
    "G": 61,
    "Date": "Tue Mar 3 2009",
    "": 0,
    "Opponent": "Memphis Grizzlies",
    "Tm": 99,
    "Opp": 89,
    "W": 49,
    "L": 12,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 62,
    "Date": "Fri Mar 6 2009",
    "": 0,
    "Opponent": "Minnesota Timberwolves",
    "Tm": 110,
    "Opp": 90,
    "W": 50,
    "L": 12,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 63,
    "Date": "Mon Mar 9 2009",
    "": 0,
    "Opponent": "Portland Trail Blazers",
    "Tm": 94,
    "Opp": 111,
    "W": 50,
    "L": 13,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 64,
    "Date": "Wed Mar 11 2009",
    "": 0,
    "Opponent": "Houston Rockets",
    "Tm": 102,
    "Opp": 96,
    "W": 51,
    "L": 13,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 65,
    "Date": "Thu Mar 12 2009",
    "": 0,
    "Opponent": "San Antonio Spurs",
    "Tm": 102,
    "Opp": 95,
    "W": 52,
    "L": 13,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 66,
    "Date": "Sun Mar 15 2009",
    "": 0,
    "Opponent": "Dallas Mavericks",
    "Tm": 107,
    "Opp": 100,
    "W": 53,
    "L": 13,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 67,
    "Date": "Tue Mar 17 2009",
    "": 0,
    "Opponent": "Philadelphia 76ers",
    "Tm": 93,
    "Opp": 94,
    "W": 53,
    "L": 14,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 68,
    "Date": "Thu Mar 19 2009",
    "": 0,
    "Opponent": "Golden State Warriors",
    "Tm": 114,
    "Opp": 106,
    "W": 54,
    "L": 14,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 69,
    "Date": "Sat Mar 21 2009",
    "": 0,
    "Opponent": "Chicago Bulls",
    "Tm": 117,
    "Opp": 109,
    "W": 55,
    "L": 14,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 70,
    "Date": "Tue Mar 24 2009",
    "": 0,
    "Opponent": "Oklahoma City Thunder",
    "Tm": 107,
    "Opp": 89,
    "W": 56,
    "L": 14,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 71,
    "Date": "Thu Mar 26 2009",
    "": 0,
    "Opponent": "Detroit Pistons",
    "Tm": 92,
    "Opp": 77,
    "W": 57,
    "L": 14,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 72,
    "Date": "Fri Mar 27 2009",
    "": 0,
    "Opponent": "New Jersey Nets",
    "Tm": 103,
    "Opp": 95,
    "W": 58,
    "L": 14,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 73,
    "Date": "Sun Mar 29 2009",
    "": 0,
    "Opponent": "Atlanta Hawks",
    "Tm": 76,
    "Opp": 86,
    "W": 58,
    "L": 15,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 74,
    "Date": "Tue Mar 31 2009",
    "": 0,
    "Opponent": "Charlotte Bobcats",
    "Tm": 84,
    "Opp": 94,
    "W": 58,
    "L": 16,
    "Streak": "L 2",
    "Notes": 0
  },
  {
    "G": 75,
    "Date": "Wed Apr 1 2009",
    "": 0,
    "Opponent": "Milwaukee Bucks",
    "Tm": 104,
    "Opp": 98,
    "W": 59,
    "L": 16,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 76,
    "Date": "Fri Apr 3 2009",
    "": 0,
    "Opponent": "Houston Rockets",
    "Tm": 93,
    "Opp": 81,
    "W": 60,
    "L": 16,
    "Streak": "W 2",
    "Notes": 0
  },
  {
    "G": 77,
    "Date": "Sun Apr 5 2009",
    "": 0,
    "Opponent": "Los Angeles Clippers",
    "Tm": 88,
    "Opp": 85,
    "W": 61,
    "L": 16,
    "Streak": "W 3",
    "Notes": 0
  },
  {
    "G": 78,
    "Date": "Tue Apr 7 2009",
    "": 0,
    "Opponent": "Sacramento Kings",
    "Tm": 122,
    "Opp": 104,
    "W": 62,
    "L": 16,
    "Streak": "W 4",
    "Notes": 0
  },
  {
    "G": 79,
    "Date": "Thu Apr 9 2009",
    "": 0,
    "Opponent": "Denver Nuggets",
    "Tm": 116,
    "Opp": 102,
    "W": 63,
    "L": 16,
    "Streak": "W 5",
    "Notes": 0
  },
  {
    "G": 80,
    "Date": "Fri Apr 10 2009",
    "": 0,
    "Opponent": "Portland Trail Blazers",
    "Tm": 98,
    "Opp": 106,
    "W": 63,
    "L": 17,
    "Streak": "L 1",
    "Notes": 0
  },
  {
    "G": 81,
    "Date": "Sun Apr 12 2009",
    "": 0,
    "Opponent": "Memphis Grizzlies",
    "Tm": 92,
    "Opp": 75,
    "W": 64,
    "L": 17,
    "Streak": "W 1",
    "Notes": 0
  },
  {
    "G": 82,
    "Date": "Tue Apr 14 2009",
    "": 0,
    "Opponent": "Utah Jazz",
    "Tm": 125,
    "Opp": 112,
    "W": 65,
    "L": 17,
    "Streak": "W 2",
    "Notes": 0
  }
]